import { useCallback, useEffect, useMemo, useState } from "react";
import { Link, useParams, useSearchParams } from "react-router-dom";
import { useChat } from "@ai-sdk/react";
import { DefaultChatTransport, type UIMessage } from "ai";
import {
  Conversation,
  ConversationContent,
  ConversationEmptyState,
  ConversationScrollButton,
} from "@/components/ai-elements/conversation";
import {
  Message,
  MessageContent,
} from "@/components/ai-elements/message";
import {
  PromptInput,
  PromptInputBody,
  PromptInputSubmit,
  PromptInputTextarea,
  type PromptInputMessage,
} from "@/components/ai-elements/prompt-input";
import { MessageParts } from "../components/session/MessageParts";
import { extractPendingFromMessages } from "../components/session/decision-types";
import { ErrorBanner } from "../components/ErrorBanner";
import { Layout } from "../components/Layout";
import { LoadingState } from "../components/LoadingState";
import { WorkspaceSubnav } from "../components/WorkspaceSubnav";
import {
  getOrCreateSession,
  getWorkspace,
  type OperatorSessionDto,
  type WorkspaceConfig,
} from "../api";
import { workspaceHref } from "../lib/workspace-path";
import { Button } from "@/components/ui/button";
import { buttonVariants } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { MessageSquareIcon } from "lucide-react";
import { cn } from "@/lib/utils";

function sessionMessagesToUI(
  session: OperatorSessionDto,
): UIMessage[] {
  return session.messages.map((m) => ({
    id: m.id,
    role: m.role,
    parts: m.parts.map((p) => {
      if (p.type === "text" && "text" in p) {
        return { type: "text" as const, text: p.text };
      }
      if (p.type.startsWith("tool-")) {
        const tool = p as {
          type: string;
          toolCallId?: string;
          state?: string;
          input?: unknown;
          output?: unknown;
          errorText?: string;
        };
        return {
          type: tool.type as `tool-${string}`,
          toolCallId: tool.toolCallId ?? tool.type,
          state: (tool.state as "output-available") ?? "output-available",
          input: tool.input,
          output: tool.output,
          errorText: tool.errorText,
        } as UIMessage["parts"][number];
      }
      if (p.type.startsWith("data-")) {
        const dataPart = p as { type: string; id?: string; data?: unknown };
        return {
          type: dataPart.type as `data-${string}`,
          id: dataPart.id,
          data: dataPart.data,
        } as UIMessage["parts"][number];
      }
      return { type: "text" as const, text: JSON.stringify(p) };
    }),
  }));
}

export function WorkspaceSessionPage() {
  const { id = "" } = useParams<{ id: string }>();
  const [searchParams] = useSearchParams();
  const rootPathHint = searchParams.get("rootPath") ?? undefined;

  const [workspace, setWorkspace] = useState<WorkspaceConfig | null>(null);
  const [sessionMeta, setSessionMeta] = useState<OperatorSessionDto | null>(
    null,
  );
  const [bootError, setBootError] = useState<unknown>(null);
  const [loading, setLoading] = useState(true);

  // Boot workspace + session
  useEffect(() => {
    if (!id) {
      return;
    }
    let cancelled = false;
    void (async () => {
      setLoading(true);
      setBootError(null);
      try {
        const ws = await getWorkspace(id, rootPathHint);
        if (cancelled) {
          return;
        }
        setWorkspace(ws.workspace);
        const { session } = await getOrCreateSession(
          id,
          ws.workspace.rootPath ?? rootPathHint,
        );
        if (cancelled) {
          return;
        }
        setSessionMeta(session);
      } catch (err) {
        if (!cancelled) {
          setBootError(err);
        }
      } finally {
        if (!cancelled) {
          setLoading(false);
        }
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [id, rootPathHint]);

  return (
    <Layout>
      <div
        data-testid="session-chat-page"
        className="flex h-[calc(100vh-2rem)] max-h-[900px] flex-col gap-3"
      >
        <header className="page-header shrink-0">
          <p className="breadcrumb">
            <Link to="/workspaces">Workspaces</Link>
            <span aria-hidden="true"> / </span>
            <Link to={workspaceHref(id, "", rootPathHint)}>
              {workspace?.name ?? id}
            </Link>
            <span aria-hidden="true"> / </span>
            <span>Session</span>
          </p>
          <div className="flex flex-wrap items-center justify-between gap-2">
            <div>
              <h1>Session</h1>
              <p className="muted text-sm">
                Conversational workspace for wiki planning, tools, and decisions.
                Options are generated by the agent — not fixed product buttons.
              </p>
            </div>
            <div className="flex items-center gap-2">
              {sessionMeta ? (
                <Badge variant="secondary" data-testid="session-status">
                  {sessionMeta.status}
                </Badge>
              ) : null}
              <Link
                to={workspaceHref(id, "/run", rootPathHint)}
                className={cn(buttonVariants({ variant: "outline", size: "sm" }))}
                data-testid="session-open-runs"
              >
                Run jobs
              </Link>
            </div>
          </div>
        </header>

        {id ? <WorkspaceSubnav workspaceId={id} /> : null}
        <ErrorBanner
          error={bootError}
          onDismiss={() => {
            setBootError(null);
          }}
        />

        {loading || !sessionMeta || !workspace ? (
          <LoadingState label="Loading session…" />
        ) : (
          <SessionChatPanel
            workspaceId={id}
            workspace={workspace}
            session={sessionMeta}
            rootPathHint={rootPathHint}
          />
        )}
      </div>
    </Layout>
  );
}

function SessionChatPanel({
  workspaceId,
  workspace,
  session,
  rootPathHint,
}: {
  workspaceId: string;
  workspace: WorkspaceConfig;
  session: OperatorSessionDto;
  rootPathHint?: string;
}) {
  const [input, setInput] = useState("");
  const [linkedRunId, setLinkedRunId] = useState(
    session.workflow?.linkedRunId as string | undefined,
  );
  const [gateStep, setGateStep] = useState<"plan-gate" | "publish-gate">(
    session.workflow?.phase === "awaiting_publish"
      ? "publish-gate"
      : "plan-gate",
  );
  const [resumePlan, setResumePlan] = useState(session.workflow?.plan);

  const chatApi = useMemo(() => {
    const base = `/api/workspaces/${encodeURIComponent(workspaceId)}/sessions/${encodeURIComponent(session.id)}/chat`;
    const root = workspace.rootPath ?? rootPathHint;
    if (root) {
      return `${base}?${new URLSearchParams({ rootPath: root }).toString()}`;
    }
    return base;
  }, [workspaceId, session.id, workspace.rootPath, rootPathHint]);

  const transport = useMemo(
    () =>
      new DefaultChatTransport({
        api: chatApi,
        prepareSendMessagesRequest: ({ messages: msgs }) => {
          const last = msgs[msgs.length - 1];
          let resumeData: { action: "approve" | "deny"; plan?: typeof resumePlan } | undefined;
          if (last?.role === "user") {
            for (const p of last.parts ?? []) {
              if (
                p.type === "text" &&
                typeof p.text === "string" &&
                (p.text === "approve" || p.text === "deny")
              ) {
                resumeData = { action: p.text };
              }
            }
          }

          // Prefer live state; fall back to parsing assistant transcript for run id / gate.
          let runId = linkedRunId;
          let step = gateStep;
          const plan = resumePlan;
          for (const m of msgs) {
            if (m.role !== "assistant") {
              continue;
            }
            for (const p of m.parts ?? []) {
              if (p.type === "text" && typeof p.text === "string") {
                const runMatch = p.text.match(/Wiki Run\s+`([0-9a-f-]{8,})`/i);
                if (runMatch?.[1]) {
                  runId = runMatch[1];
                }
                if (/Publish the staged wiki/i.test(p.text)) {
                  step = "publish-gate";
                } else if (/Proposed wiki plan/i.test(p.text)) {
                  step = "plan-gate";
                }
              }
              if (
                p.type === "data-choice" &&
                p.data &&
                typeof p.data === "object" &&
                "question" in (p.data as object)
              ) {
                const q = String((p.data as { question?: string }).question ?? "");
                if (/publish/i.test(q)) {
                  step = "publish-gate";
                } else if (/plan/i.test(q)) {
                  step = "plan-gate";
                }
              }
            }
          }

          if (resumeData && step === "plan-gate" && plan) {
            resumeData = { ...resumeData, plan };
          }

          return {
            body: {
              messages: msgs,
              ...(resumeData && runId
                ? {
                    resumeData,
                    runId,
                    step,
                  }
                : {}),
            },
          };
        },
      }),
    [chatApi, linkedRunId, gateStep, resumePlan],
  );

  const initialMessages = useMemo(
    () => sessionMessagesToUI(session),
    [session],
  );

  const { messages, sendMessage, status, stop, error, clearError } = useChat({
    id: session.id,
    transport,
    messages: initialMessages,
  });

  const pending = useMemo(
    () => extractPendingFromMessages(messages),
    [messages],
  );

  // Track workflow run id / gate from streamed assistant text + decisions.
  useEffect(() => {
    for (const m of messages) {
      if (m.role !== "assistant") {
        continue;
      }
      for (const p of m.parts ?? []) {
        if (p.type === "text" && typeof p.text === "string") {
          const runMatch = p.text.match(/Wiki Run\s+`([0-9a-f-]{8,})`/i);
          if (runMatch?.[1]) {
            setLinkedRunId(runMatch[1]);
          }
          if (/Publish the staged wiki/i.test(p.text)) {
            setGateStep("publish-gate");
          }
          if (/Proposed wiki plan/i.test(p.text)) {
            setGateStep("plan-gate");
          }
        }
        if (
          p.type === "data-choice" &&
          p.data &&
          typeof p.data === "object" &&
          "options" in (p.data as object)
        ) {
          const q = (p.data as { question?: string }).question ?? "";
          if (/publish/i.test(q)) {
            setGateStep("publish-gate");
          } else if (/plan/i.test(q)) {
            setGateStep("plan-gate");
          }
        }
      }
    }
    if (session.workflow?.plan) {
      setResumePlan(session.workflow.plan);
    }
  }, [messages, session.workflow?.plan]);
  const choiceOnly = pending?.mode === "choice_only";
  const inputOnly = pending?.mode === "input_only";
  const canType = !choiceOnly;
  const isBusy = status === "submitted" || status === "streaming";
  const hasSources = (workspace.sources?.length ?? 0) > 0;

  const latestAssistantId = useMemo(() => {
    for (let i = messages.length - 1; i >= 0; i--) {
      if (messages[i]!.role === "assistant") {
        return messages[i]!.id;
      }
    }
    return null;
  }, [messages]);

  const handleChoice = useCallback(
    (optionId: string) => {
      if (isBusy) {
        return;
      }
      // Option ids are workflow resume actions: approve | deny (and aliases).
      const action =
        optionId === "approve" ||
        optionId === "approve_write" ||
        optionId === "publish_now"
          ? "approve"
          : optionId === "deny" ||
              optionId === "reject_plan" ||
              optionId === "keep_staging"
            ? "deny"
            : optionId;
      void sendMessage({ text: action });
    },
    [isBusy, sendMessage],
  );

  const handleSubmit = useCallback(
    (message: PromptInputMessage) => {
      const text = message.text.trim();
      if (!text || isBusy || choiceOnly) {
        return;
      }
      void sendMessage({ text });
      setInput("");
    },
    [choiceOnly, isBusy, sendMessage],
  );

  return (
    <>
      <ErrorBanner error={error} onDismiss={() => clearError()} />
      <div className="flex min-h-0 flex-1 flex-col rounded-lg border bg-card">
        <div className="flex items-center justify-end gap-2 border-b px-3 py-2">
          <Badge variant="secondary" data-testid="session-chat-status">
            {status}
          </Badge>
          {isBusy ? (
            <Button
              type="button"
              variant="destructive"
              size="sm"
              onClick={() => stop()}
              data-testid="session-stop"
            >
              Stop
            </Button>
          ) : null}
        </div>
        <Conversation className="min-h-0" data-testid="session-conversation">
          <ConversationContent className="gap-4 p-4">
            {messages.length === 0 ? (
              <ConversationEmptyState
                icon={<MessageSquareIcon className="size-10" />}
                title="Start a wiki conversation"
                description='Try “generate a wiki plan” — then choose a dynamic option or type revision notes.'
              />
            ) : (
              messages.map((message) => (
                <Message from={message.role} key={message.id}>
                  <MessageContent>
                    <MessageParts
                      message={message}
                      isLatestAssistant={message.id === latestAssistantId}
                      onChoice={handleChoice}
                    />
                  </MessageContent>
                </Message>
              ))
            )}
          </ConversationContent>
          <ConversationScrollButton />
        </Conversation>

        <div className="border-t p-3">
          {choiceOnly ? (
            <p
              className="mb-2 text-xs text-muted-foreground"
              data-testid="session-composer-locked"
            >
              Select an option above to continue (free text is disabled for this
              step).
            </p>
          ) : null}
          {inputOnly && pending ? (
            <p className="mb-2 text-xs text-muted-foreground">
              {pending.question}
              {pending.inputPlaceholder
                ? ` — ${pending.inputPlaceholder}`
                : ""}
            </p>
          ) : null}
          <PromptInput
            onSubmit={handleSubmit}
            className="w-full"
            data-testid="session-prompt"
          >
            <PromptInputBody>
              <PromptInputTextarea
                value={input}
                onChange={(e) => setInput(e.currentTarget.value)}
                disabled={!canType || isBusy || !hasSources}
                placeholder={
                  !hasSources
                    ? "Add a source first (Sources tab)"
                    : choiceOnly
                      ? "Select an option above…"
                      : (pending?.inputPlaceholder ?? "Message the wiki agent…")
                }
                data-testid="session-input"
              />
            </PromptInputBody>
            <PromptInputSubmit
              status={isBusy ? "streaming" : "ready"}
              disabled={
                isBusy || choiceOnly || !canType || !input.trim() || !hasSources
              }
              data-testid="session-send"
              onStop={() => stop()}
            />
          </PromptInput>
        </div>
      </div>
    </>
  );
}
