"""Deterministic repository facts for Discover (`okf scan`) and module detection.

Everything is read from git HEAD of each source (tracked files and blobs, never
the working tree). The wiki directory and forbidden (secret) files are invisible.
"""

import fnmatch
import json
import re
import shlex
from collections import Counter, defaultdict
from dataclasses import dataclass
from itertools import combinations
from pathlib import PurePosixPath
from typing import ClassVar
from xml.etree import ElementTree

import tomllib
import yaml

import _code
import _config
import _files
import _git

MAX_BYTES = 1 << 20
LIMITS = {
    "entry_points": 50, "commands": 80, "docs": 80, "terms": 50, "configs": 60,
    "ci_files": 30, "ci_steps": 80, "triggers": 100, "deps": 60, "central": 20,
    "resources": 40,
}
MAX_CO_CHANGE = 30
MAX_TEST_DIRS = 20
MAX_SAME_CONFIG = 3  # paths per (kind, file name)
CO_CHANGE_COMMITS = 500
CO_CHANGE_MAX_FILES = 50
CO_CHANGE_SUPPORT = 3
CO_CHANGE_CONFIDENCE = 0.6

# Code languages by lowercase suffix. A file with one of these suffixes is a
# "code file" for module detection, language counts and term analysis.
LANGUAGES = {
    ".py": "Python", ".pyi": "Python",
    ".java": "Java", ".kt": "Kotlin", ".kts": "Kotlin", ".scala": "Scala",
    ".groovy": "Groovy",
    ".ts": "TypeScript", ".tsx": "TypeScript", ".mts": "TypeScript", ".cts": "TypeScript",
    ".js": "JavaScript", ".jsx": "JavaScript", ".mjs": "JavaScript", ".cjs": "JavaScript",
    ".vue": "Vue", ".svelte": "Svelte",
    ".go": "Go", ".rs": "Rust", ".zig": "Zig",
    ".c": "C", ".h": "C", ".cc": "C++", ".cpp": "C++", ".cxx": "C++", ".hpp": "C++",
    ".hh": "C++", ".cs": "C#", ".fs": "F#", ".m": "Objective-C", ".mm": "Objective-C",
    ".swift": "Swift", ".dart": "Dart",
    ".rb": "Ruby", ".php": "PHP", ".pl": "Perl", ".lua": "Lua", ".r": "R", ".jl": "Julia",
    ".ex": "Elixir", ".exs": "Elixir", ".erl": "Erlang", ".clj": "Clojure",
    ".hs": "Haskell", ".ml": "OCaml",
    ".sql": "SQL", ".sh": "Shell", ".bash": "Shell", ".ps1": "PowerShell",
}
DOC_SUFFIXES = {".md", ".mdx", ".markdown", ".rst", ".adoc", ".txt"}
BINARY_EXT = {
    ".png", ".jpg", ".jpeg", ".gif", ".webp", ".ico", ".pdf", ".zip", ".gz", ".jar",
    ".class", ".so", ".dll", ".exe", ".woff", ".woff2", ".ttf", ".eot", ".mp4", ".mp3",
    ".wasm",
}
GENERATED_TOKEN = re.compile(
    r"(^|/)(generated|vendor|dist|build|node_modules|third_party)(/|$)", re.IGNORECASE
)
GENERATED_MARKERS = ("generated by", "generated file", "do not edit")

# Files that name a module's own build (checked in this order).
MANIFESTS = (
    "package.json", "pyproject.toml", "Cargo.toml", "go.mod", "pom.xml",
    "build.gradle.kts", "build.gradle", "setup.py", "composer.json", "Gemfile",
    "mix.exs", "CMakeLists.txt",
)
ENTRY_BASENAMES = {
    "main.py", "__main__.py", "app.py", "server.py", "cli.py", "manage.py", "wsgi.py",
    "asgi.py", "main.ts", "main.js", "index.ts", "index.js", "app.ts", "app.js",
    "server.ts", "server.js", "main.go", "main.rs", "main.java", "main.kt",
    "program.cs", "main.c", "main.cpp",
}
ENTRY_SPECS = {
    "dockerfile", "openapi.json", "openapi.yaml", "openapi.yml", "swagger.json",
    "swagger.yaml", "swagger.yml", "asyncapi.json", "asyncapi.yaml", "asyncapi.yml",
    "web.xml",
}
LOCK_NAMES = {
    "package-lock.json", "pnpm-lock.yaml", "yarn.lock", "go.sum", "cargo.lock",
    "uv.lock", "poetry.lock",
}
# --- the test-path rule ---------------------------------------------------------------
#
# One definition of "test code" for modules, entry points, commands, build roots, terms
# and the ``tests`` fact. A path is a test path when a directory above it is a test root
# or test-support directory (outside a Maven/Gradle ``src/main`` tree), or its file name
# follows a test-runner naming convention. A name that merely contains "test" inside a
# word (latest.py, contest/, attestation.py, Testimonial.java, testing_utils.py) is not.

# camelCase test source sets and targets: integrationTest, MyAppTests, FooUnitTests.
_TEST_ROOT_CAMEL = re.compile(r"[a-z0-9](Unit|Integration|Functional)?Tests?$")
# Test roots by name, any case: tests, spec, e2e, testing; Foo.Tests, api-tests, it_test.
_TEST_ROOT = re.compile(
    r"^((tests?|specs?|__tests__|testing|e2e)"
    r"|.+[._-](unit|integration|functional|e2e)?tests?)$",
    re.IGNORECASE,
)
# Directories that hold test data or doubles: their files are test paths, but they are
# not where tests are written, so they are not reported as test directories.
_TEST_SUPPORT = re.compile(
    r"^(testdata|test[-_]data|fixtures?|__fixtures__|__mocks__|__snapshots__)$", re.IGNORECASE
)
_TEST_FILES = {"conftest.py"}
_SPEC_SUFFIXES = {".groovy", ".scala", ".kt"}  # Spock, ScalaTest/specs2, Kotest


def _test_root(part: str) -> bool:
    """A directory name that holds tests: ``tests``, ``src/test``, ``e2e``,
    ``Foo.Tests``, ``api-tests``, ``integrationTest`` (camelCase needs the capital)."""
    return bool(_TEST_ROOT.match(part) or _TEST_ROOT_CAMEL.search(part))


def _test_dir(part: str) -> bool:
    """A test root or a test-support directory (fixtures, testdata, __mocks__)."""
    return _test_root(part) or bool(_TEST_SUPPORT.match(part))


def _test_dirs(rel: str) -> list[str]:
    """Directory names of ``rel`` that can make it a test path: all of them up to a
    ``src/main`` source set (production code even in a package named ``test``)."""
    parts = rel.split("/")[:-1]
    for index in range(1, len(parts)):
        if parts[index] == "main" and parts[index - 1] == "src":
            return parts[:index]
    return parts


def is_test_path(rel: str) -> bool:
    """Whether a source-relative path is test code, test data or a test double."""
    name = rel.rsplit("/", 1)[-1]
    if name in _TEST_FILES or _test_name(name):
        return True
    return any(_test_dir(part) for part in _test_dirs(rel))


def _test_name(name: str) -> str | None:
    """The naming convention a test file name follows, as a glob, else None:
    ``test_*.py``; ``*_test.go``, ``*.test.ts``, ``*-spec.js``, ``*_spec.rb``;
    ``*Test.java``, ``*Tests.swift``, ``*IT.java`` after a lowercase letter or digit, and
    ``*Spec.scala`` likewise in Groovy, Scala and Kotlin only. A ``Test`` prefix (JUnit 3
    ``TestFoo.java``) is no rule of its own: production classes use it too (a
    ``TestResource`` endpoint); ``_test_pattern`` reports it inside test roots."""
    suffix = PurePosixPath(name).suffix
    if not suffix:
        return None
    base = name[: -len(suffix)]
    if base.startswith("test_") and len(base) > 5:
        return f"test_*{suffix}"
    for middle in ("_test", ".test", "-test", "_spec", ".spec", "-spec"):
        if base.endswith(middle) and len(base) > len(middle):
            return f"*{middle}{suffix}"
    for tail in ("Tests", "Test", "IT", "Spec"):
        if tail == "Spec" and suffix not in _SPEC_SUFFIXES:
            continue  # java.security.spec.KeySpec: Spec types are production code in Java
        if base.endswith(tail) and len(base) > len(tail):
            before = base[-len(tail) - 1]
            if before.islower() or before.isdigit():
                return f"*{tail}{suffix}"
    return None

# (kind, lowercase basename globs)
CONFIG_NAMES = (
    ("lint", (
        "ruff.toml", ".ruff.toml", ".eslintrc", ".eslintrc.*", "eslint.config.*",
        ".golangci.yml", ".golangci.yaml", ".golangci.toml", ".golangci.json",
        "clippy.toml", ".clippy.toml", "checkstyle*.xml", ".flake8", ".pylintrc",
        "pylintrc", ".stylelintrc*", "stylelint.config.*", "biome.json", "biome.jsonc",
        ".rubocop.yml", ".swiftlint.yml", ".markdownlint*", "spotbugs*.xml",
        "findbugs*.xml", "pmd*.xml", "detekt*.yml",
    )),
    ("format", (
        ".prettierrc", ".prettierrc.*", "prettier.config.*", "rustfmt.toml",
        ".rustfmt.toml", "biome.json", "biome.jsonc", ".clang-format", ".scalafmt.conf",
    )),
    ("typecheck", ("tsconfig*.json", "jsconfig*.json", "mypy.ini", ".mypy.ini",
                   "pyrightconfig.json")),
    ("test", (
        "pytest.ini", "tox.ini", "noxfile.py", "jest.config.*", "vitest.config.*",
        "vitest.workspace.*", "karma.conf.*", ".mocharc*", "playwright.config.*",
        "cypress.config.*", ".coveragerc", "phpunit.xml*",
    )),
    ("build", (
        "makefile", "gnumakefile", "justfile", ".justfile", "taskfile.yml",
        "taskfile.yaml", "cmakelists.txt", "dockerfile", "docker-compose*.yml",
        "docker-compose*.yaml", "compose.yml", "compose.yaml", "webpack.config.*",
        "vite.config.*", "rollup.config.*", "tsup.config.*", "turbo.json", "nx.json",
        "lerna.json", "pnpm-workspace.yaml", "go.work", "settings.gradle",
        "settings.gradle.kts", "build.bazel", "module.bazel", "workspace.bazel",
        "meson.build", "mvnw", "gradlew",
    )),
    ("precommit", (".pre-commit-config.yaml", ".pre-commit-config.yml", "lefthook.yml",
                   "lefthook.yaml", ".lintstagedrc*", "lint-staged.config.*")),
    ("editor", (".editorconfig",)),
)
_CONFIG_REGEX = tuple(
    (kind, re.compile("|".join(fnmatch.translate(p) for p in patterns)))
    for kind, patterns in CONFIG_NAMES
)
PYPROJECT_TOOLS = {
    "ruff": "lint", "pylint": "lint", "flake8": "lint", "mypy": "typecheck",
    "pyright": "typecheck", "pytest": "test", "coverage": "test", "black": "format",
    "isort": "format",
}
INI_SECTIONS = (
    (re.compile(r"^(flake8|pycodestyle|pylint.*)$"), "lint"),
    (re.compile(r"^mypy(-.*)?$"), "typecheck"),
    (re.compile(r"^(tool:pytest|pytest|coverage:.*)$"), "test"),
    (re.compile(r"^isort$"), "format"),
)
PACKAGE_JSON_KEYS = {"eslintConfig": "lint", "prettier": "format", "jest": "test"}

DEFINED_STOP = {
    "note", "notes", "warning", "important", "tip", "example", "examples", "caution",
    "danger", "info", "todo", "fixme", "deprecated", "default", "required", "optional",
    "usage", "description", "returns", "return", "parameters", "params", "args",
    "arguments", "input", "output", "status", "type", "name", "summary", "see also",
    "prerequisites", "why", "what", "how", "when", "where", "pros", "cons", "yes", "no",
    "before", "after", "problem", "solution", "context", "decision", "consequences",
    "result", "results", "goal", "goals", "step", "steps", "options", "option", "value",
}

_WORD = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")
_CAPITALIZED = re.compile(r"\b[A-Z][A-Za-z0-9_]*")
_CAMEL = re.compile(r"(?:[A-Z][a-z0-9]+){2,}")
_BOLD_DEF = re.compile(
    r"\*\*([^*\n]{2,60}?)\*\*[ \t]*(?::|：|—|–|[ \t]is[ \t])|\*\*([^*\n]{2,60}?)[:：]\*\*"
)
_LIST_ITEM = re.compile(r"^[ \t]*(?:[-*+]|\d+[.)])[ \t]+$")  # text before the bold opens a list item
_CJK = re.compile(r"[\u3400-\u9fff\uf900-\ufaff]")
_TYPE_DEF = re.compile(
    r"^[ \t]*(?:(?:export|default|public|private|protected|internal|abstract|final|"
    r"sealed|data|static|open|partial|readonly|declare|case|pub(?:\([^)]*\))?)\s+)*"
    r"(?:class|struct|interface|trait|type|record|object|protocol|enum)\s+([A-Z]\w*)",
    re.MULTILINE,
)
_PY_ENUM = re.compile(r"^([ \t]*)class\s+(\w+)\s*\(([^)]*)\)\s*:", re.MULTILINE)
_PY_ENUM_BASE = re.compile(r"\b(Enum|IntEnum|StrEnum|Flag|IntFlag)\b")
_BRACE_ENUM = re.compile(r"\benum\s+(?:class\s+)?([A-Za-z_]\w*)[^{;=]*\{")
_GO_CONST = re.compile(r"^const\s*\(\s*$", re.MULTILINE)
_C_NOISE = re.compile(
    r"\"(?:\\.|[^\"\\\n])*\"|'(?:\\.|[^'\\\n])*'|//[^\n]*|/\*.*?\*/", re.DOTALL
)
_BRACE_ENUM_SUFFIXES = {".java", ".kt", ".ts", ".tsx", ".mts", ".cts", ".rs", ".cs",
                        ".scala", ".swift", ".cpp", ".hpp", ".cc", ".h", ".c", ".dart"}


@dataclass(frozen=True)
class Module:
    path: str  # workspace-relative ("." for a single repo root; hub paths carry the source)
    source: str
    manifest: str | None


# --- source tree at HEAD -------------------------------------------------------


class _Tree:
    """One source at HEAD: visible tracked files and blob text access."""

    def __init__(
        self,
        ws: _config.Workspace,
        source: _config.Source,
        blobs: _git.BlobReader,
        head: str | None = None,
        listing: list[str] | None = None,
    ):
        self.source = source
        self.head = head or _git.head(source.path)
        wiki = None if ws.hub else ws.wiki_rel
        if listing is None:
            listing = _git.ls_files(source.path, self.head)
        self.files = [
            path
            for path in listing
            if not (wiki and _under(path, wiki)) and not _config.is_forbidden(path)
        ]
        self.fileset = set(self.files)
        self._blobs = blobs
        self._cache: dict[str, str | None] = {}

    def ws(self, rel: str) -> str:
        """Workspace-relative path of a source-relative path ("." is the source root)."""
        if rel == ".":
            return self.source.name if self.source.prefix else "."
        return self.source.prefix + rel

    def loc(self, rel: str, line: int) -> str:
        return _config.Locator(self.ws(rel), line, line).text()  # <path>#Ln for a path with spaces

    def text(self, rel: str, cache: bool = True) -> str | None:
        """Decoded blob text; None when missing, binary or larger than 1 MiB.

        Manifests and build files are read by several extractors, so texts are
        memoized unless ``cache`` is false (the one pass over every file).
        """
        if rel in self._cache:
            return self._cache[rel]
        text = None
        if rel in self.fileset and _suffix(rel) not in BINARY_EXT:
            data = self._blobs.read(self.head, rel)
            if data is not None and len(data) <= MAX_BYTES and b"\0" not in data[:8192]:
                text = data.decode("utf-8", errors="replace")
        if cache:
            self._cache[rel] = text
        return text

    def texts(self, rels: list[str]):
        """Yield (path, text or None) like ``text`` for many paths, pipelined and uncached."""
        wanted = [rel for rel in rels if rel in self.fileset and _suffix(rel) not in BINARY_EXT]
        for rel, data in self._blobs.read_many(self.head, wanted):
            if data is None or len(data) > MAX_BYTES or b"\0" in data[:8192]:
                yield rel, None
            else:
                yield rel, data.decode("utf-8", errors="replace")


def _under(path: str, prefix: str) -> bool:
    return path == prefix or path.startswith(prefix + "/")


def _suffix(path: str) -> str:
    """Lowercase extension of the last segment, as PurePosixPath.suffix."""
    name = path.rsplit("/", 1)[-1]
    dot = name.rfind(".")
    if dot <= 0 or dot == len(name) - 1:
        return ""
    return name[dot:].lower()


def _name(path: str) -> str:
    return path.rsplit("/", 1)[-1]


def _parent(path: str) -> str:
    return path.rsplit("/", 1)[0] if "/" in path else "."


def command_cwd(rel: str, command: str) -> str:
    """Source-relative directory a command runs from, given the source-relative file
    its locator names: the source root when the command names that file by its
    source-root path (``uv run evals/run_e2e.py``, a PEP 723 script), else the
    file's directory (``npm run build`` cited at ``web/package.json`` runs in ``web``).

    ``okf scan`` records it as each command's ``cwd``; eval_canon re-derives it the
    same way for a wiki command from the file its citation names.
    """
    parent = _parent(rel)
    if parent == ".":
        return "."
    try:
        tokens = shlex.split(command)
    except ValueError:
        tokens = command.split()
    return "." if any(token.removeprefix("./") == rel for token in tokens) else parent


def _join(base: str, rel: str) -> str:
    return rel if base in ("", ".") else f"{base}/{rel}"


def _language(path: str) -> str | None:
    return LANGUAGES.get(_suffix(path))


def _dirs(files: list[str]) -> set[str]:
    dirs: set[str] = set()
    for path in files:
        parts = path.split("/")[:-1]
        for index in range(1, len(parts) + 1):
            dirs.add("/".join(parts[:index]))
    return dirs


def _line(text: str, pos: int) -> int:
    return text.count("\n", 0, pos) + 1


def _find(lines: list[str], pattern: str, start: int = 0) -> int | None:
    """1-based number of the first line at or after index ``start`` matching ``pattern``."""
    regex = re.compile(pattern)
    for index in range(max(start, 0), len(lines)):
        if regex.search(lines[index]):
            return index + 1
    return None


def _load(kind: str, text: str | None):
    if text is None:
        return None
    try:
        if kind == "json":
            return json.loads(text)
        if kind == "toml":
            return tomllib.loads(text)
        return yaml.safe_load(text)
    except (ValueError, yaml.YAMLError):
        return None


def _dict(value) -> dict:
    return value if isinstance(value, dict) else {}


def _strings(value) -> list[str]:
    return [item for item in value if isinstance(item, str)] if isinstance(value, list) else []


def _unquote(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "'\"":
        return value[1:-1]
    return value


# --- modules --------------------------------------------------------------------


def modules(
    ws: _config.Workspace,
    heads: dict[str, str] | None = None,
    listings: dict[str, list[str]] | None = None,
) -> list[Module]:
    """Modules of every source, sorted by path (reads only manifests at HEAD).

    ``heads`` and ``listings`` (source name -> HEAD, tracked paths at HEAD) let a
    caller that already listed the sources skip a second ``git ls-tree``.
    """
    result: list[Module] = []
    for source in ws.sources:
        with _git.BlobReader(source.path) as blobs:
            tree = _Tree(
                ws, source, blobs,
                (heads or {}).get(source.name), (listings or {}).get(source.name),
            )
            found = _source_modules(tree, ws.hub)
        result += [
            Module(tree.ws(path), source.name, tree.ws(manifest) if manifest else None)
            for path, manifest in found
        ]
    return sorted(result, key=lambda module: module.path)


def _source_modules(tree: _Tree, hub: bool) -> list[tuple[str, str | None]]:
    """(source-relative module path, source-relative manifest) pairs, sorted."""
    declared = _declared(tree)
    code = [path for path in tree.files if _language(path)]
    found: dict[str, str | None] = dict(declared)
    for top in sorted({path.split("/", 1)[0] for path in code if "/" in path}):
        if top.startswith(".") or _test_dir(top) or any(_under(m, top) for m in found):
            continue  # hidden, a top-level test root, or covered by declared modules
        for path in _top_modules(tree, top, code):
            found[path] = None
    _drop_aggregators(found, code)
    if not found and (hub or any("/" not in path for path in code)):
        found["."] = None
    split = _package_modules(tree.fileset, found, code)
    attributed = {path: _attribution(tree.fileset, path, declared) for path in found}
    for path, parent in split.items():
        found[path] = None
        attributed[path] = attributed[parent]  # a package shares its build's manifest
    _drop_aggregators(found, code)
    return sorted((path, attributed[path]) for path in found)


# Top-level directories that only hold code (no build of their own): their child
# directories are the modules, as src/billing and src/payments in a src layout.
CODE_ROOTS = ("src", "lib", "app", "pkg", "internal", "packages", "source", "cmd")
# Maven/Gradle source sets: src/main and src/test are one build, not two modules.
_SOURCE_SETS = ("main",)


def _top_modules(tree: _Tree, top: str, code: list[str]) -> list[str]:
    """Modules for one top-level code directory without declared modules below it."""
    if top not in CODE_ROOTS or _own_manifest(tree.fileset, top):
        return [top]
    below = [path[len(top) + 1:] for path in code if path.startswith(top + "/")]
    children = sorted({path.split("/", 1)[0] for path in below if "/" in path})
    if any(child in _SOURCE_SETS for child in children):
        return [top]
    modules = [
        f"{top}/{child}" for child in children
        if not child.startswith(".") and not _test_dir(child)
    ]
    if any("/" not in path for path in below) or not modules:
        modules.append(top)  # code files directly in the code root
    return modules


# A package directory becomes a module of its own when its build holds at least two
# sibling packages with this many production code files each.
PACKAGE_MIN_FILES = 3
_JVM_LANG_DIRS = ("java", "kotlin", "scala", "groovy")


def _package_modules(fileset: set[str], found: dict[str, str | None], code: list[str]) -> dict[str, str]:
    """Package modules inside single builds -> the module they split.

    A JVM source set (``src/main/java``) or a Python package is followed down while
    it holds exactly one child package and no code of its own (``com/acme/shop``);
    when that base then holds two or more child packages with ``PACKAGE_MIN_FILES``
    production code files each, every such child is a module
    (``src/main/java/com/acme/shop/order``, ``src/shop/billing``). Test code stays
    with the enclosing module, and one level is split, never deeper.
    """
    owned: dict[str, list[str]] = defaultdict(list)
    for path in code:
        home = owner(path, found)
        if home is not None and not is_test_path(path):
            owned[home].append(path)
    packages = {_parent(p) for p in fileset if _name(p) == "__init__.py"}
    package_parents = {_parent(d) for d in packages}
    split: dict[str, str] = {}
    for module, files in owned.items():
        prefix = "" if module == "." else module + "/"
        bases = []
        for lang in _JVM_LANG_DIRS:
            for source_set in ("src/main/", "main/" if module.rsplit("/", 1)[-1] == "src" else None):
                if source_set and any(p.startswith(f"{prefix}{source_set}{lang}/") for p in files):
                    bases.append((f"{prefix}{source_set}{lang}", False))
        if module != "." and (module in packages or module in package_parents):
            bases.append((module, True))
        for base, python in bases:
            for child in _split_children(fileset, base, files, python):
                split[child] = module
    return split


def _split_children(fileset: set[str], base: str, files: list[str], python: bool) -> list[str]:
    below = [p for p in files if p.startswith(base + "/")]
    while True:
        rest = [p[len(base) + 1:] for p in below]
        children = {p.split("/", 1)[0] for p in rest if "/" in p}
        if len(children) != 1 or any("/" not in p for p in rest):
            break
        base = f"{base}/{children.pop()}"
        if python and f"{base}/__init__.py" not in fileset:
            return []
    counts = Counter(p[len(base) + 1:].split("/", 1)[0] for p in below if "/" in p[len(base) + 1:])
    chosen = [
        f"{base}/{child}" for child, count in sorted(counts.items())
        if count >= PACKAGE_MIN_FILES and not child.startswith((".", "_")) and not _test_dir(child)
        and (not python or f"{base}/{child}/__init__.py" in fileset)
    ]
    return chosen if len(chosen) >= 2 else []


def _attribution(fileset: set[str], path: str, declared: dict[str, str]) -> str | None:
    """The nearest manifest that owns a module: its own, else the manifest that
    declared it, else (for a code root or a directory in one) the nearest parent
    manifest, when that parent is a single build (it declares no modules)."""
    own = _own_manifest(fileset, path)
    if own or path in declared:
        return own or declared[path]
    if path == "." or path.split("/", 1)[0] not in CODE_ROOTS:
        return None
    for directory in _ancestors(_parent(path)):
        manifest = _own_manifest(fileset, directory)
        if manifest:
            if directory == ".":
                aggregates = bool(declared)
            else:
                aggregates = any(_under(m, directory) and m != directory for m in declared)
            return None if aggregates else manifest
    return None


def owner(path: str, modules) -> str | None:
    """The deepest module directory containing ``path`` (source- or workspace-relative)."""
    parts = path.split("/")[:-1]
    for index in range(len(parts), 0, -1):
        candidate = "/".join(parts[:index])
        if candidate in modules:
            return candidate
    return "." if "." in modules else None


def _drop_aggregators(found: dict[str, str | None], code: list[str]) -> None:
    """Remove modules that only aggregate nested modules (e.g. a Maven pom-packaging
    parent): they contain another module and own no code file of their own."""
    parents = {path for path in found if any(_under(other, path) and other != path for other in found)}
    if not parents:
        return
    owning = {owner(path, found) for path in code}
    for path in parents - owning:
        del found[path]


def _own_manifest(fileset: set[str], directory: str) -> str | None:
    for name in MANIFESTS:
        path = _join(directory, name)
        if path in fileset:
            return path
    return None


def _declared(tree: _Tree) -> dict[str, str]:
    """Manifest-declared module directories → the manifest that declared them."""
    fileset = tree.fileset
    dirs = _dirs(tree.files)
    found: dict[str, str] = {}

    def add(manifest: str, patterns: list[str], marker: str | None, exclude=()) -> None:
        base = _parent(manifest)
        hits: set[str] = set()
        excluded: set[str] = set()
        for pattern in patterns:
            if pattern.startswith("!"):
                excluded |= _expand(base, pattern[1:], dirs, fileset, None)
            else:
                hits |= _expand(base, pattern, dirs, fileset, marker)
        for pattern in exclude:
            excluded |= _expand(base, pattern, dirs, fileset, None)
        for path in sorted(hits - excluded):
            found.setdefault(path, manifest)

    if "package.json" in fileset:
        workspaces = _dict(_load("json", tree.text("package.json"))).get("workspaces")
        if isinstance(workspaces, dict):
            workspaces = workspaces.get("packages")
        add("package.json", _strings(workspaces), "package.json")
    if "pnpm-workspace.yaml" in fileset:
        data = _dict(_load("yaml", tree.text("pnpm-workspace.yaml")))
        add("pnpm-workspace.yaml", _strings(data.get("packages")), "package.json")
    if "Cargo.toml" in fileset:
        workspace = _dict(_dict(_load("toml", tree.text("Cargo.toml"))).get("workspace"))
        add("Cargo.toml", _strings(workspace.get("members")), "Cargo.toml",
            _strings(workspace.get("exclude")))
    if "go.work" in fileset:
        add("go.work", _go_work_uses(tree.text("go.work") or ""), "go.mod")
    for path in tree.files:
        if _name(path) == "go.mod" and "/" in path and not re.search(
            r"(^|/)(testdata|vendor|third_party)/", path
        ):
            found.setdefault(_parent(path), path)
    if "pom.xml" in fileset:
        _maven(tree, "pom.xml", found, set())
    for name in ("settings.gradle.kts", "settings.gradle"):
        if name in fileset:
            add(name, _gradle_includes(tree.text(name) or ""), None)
    if "pyproject.toml" in fileset:
        data = _dict(_load("toml", tree.text("pyproject.toml")))
        workspace = _dict(_dict(_dict(data.get("tool")).get("uv")).get("workspace"))
        add("pyproject.toml", _strings(workspace.get("members")), "pyproject.toml",
            _strings(workspace.get("exclude")))
    return found


def _norm(base: str, pattern: str) -> str | None:
    """Join a manifest-relative member path to its base; None for root or escapes."""
    pattern = pattern.strip().replace("\\", "/")
    while pattern.startswith("./"):
        pattern = pattern[2:]
    pattern = pattern.strip("/")
    if not pattern or pattern == "." or ".." in pattern.split("/"):
        return None
    return _join(base, pattern)


def _expand(base, pattern, dirs, fileset, marker) -> set[str]:
    full = _norm(base, pattern)
    if full is None:
        return set()
    if any(char in full for char in "*?["):
        hits = {d for d in dirs if _config.glob_match(full, d)}
    else:
        hits = {full} & dirs
    if marker:
        hits = {d for d in hits if f"{d}/{marker}" in fileset}
    return hits


def _go_work_uses(text: str) -> list[str]:
    uses: list[str] = []
    block = False
    for raw in _files.text_lines(text):
        line = raw.split("//", 1)[0].strip()
        if block:
            if line == ")":
                block = False
            elif line:
                uses.append(_unquote(line))
            continue
        match = re.match(r"^use\s*(.*)$", line)
        if match:
            rest = match[1].strip()
            if rest == "(":
                block = True
            elif rest:
                uses.append(_unquote(rest.strip("()")))
    return uses


def _maven(tree: _Tree, pom: str, found: dict[str, str], seen: set[str]) -> None:
    if pom in seen:
        return
    seen.add(pom)
    try:
        root = ElementTree.fromstring(tree.text(pom) or "")
    except ElementTree.ParseError:
        return
    base = _parent(pom)
    items = root.findall("./{*}modules/{*}module") + root.findall(
        "./{*}profiles/{*}profile/{*}modules/{*}module"
    )
    for item in items:
        path = _norm(base, item.text or "")
        if path and f"{path}/pom.xml" in tree.fileset:
            found.setdefault(path, pom)
            _maven(tree, f"{path}/pom.xml", found, seen)


def _gradle_includes(text: str) -> list[str]:
    text = re.sub(r"//[^\n]*|/\*.*?\*/", "", text, flags=re.DOTALL)
    names: list[str] = []
    for match in re.finditer(r"\binclude\b\s*(\()?", text):
        if match[1]:
            end = text.find(")", match.end())
            chunk = text[match.end(): end if end >= 0 else len(text)]
        else:
            chunk_lines = []
            for line in text[match.end():].split("\n"):
                chunk_lines.append(line)
                if not line.rstrip().endswith(","):
                    break
            chunk = "\n".join(chunk_lines)
        names += re.findall(r"[\"']([^\"']+)[\"']", chunk)
    return [name.strip(":").replace(":", "/") for name in names]


# --- scan ---------------------------------------------------------------------------


def scan(ws: _config.Workspace) -> dict:
    sources, mods, entries, commands, ci_files, configs = [], [], [], [], [], set()
    test_dirs: Counter = Counter()
    test_patterns: set[str] = set()
    docs: list[str] = []
    terms = _Terms()
    imports = _code.Imports()
    found_triggers: list[Trigger] = []
    named: list[tuple[str, str, str, int]] = []  # (kind, name, file, line)
    co_change: list[dict] = []
    for source in ws.sources:
        clean, dirty = _git.is_clean(source.path, [] if ws.hub else [ws.wiki_rel])
        with _git.BlobReader(source.path) as blobs:
            tree = _Tree(ws, source, blobs)
            shallow = _git.is_shallow(source.path)
            sources.append({"name": source.name, "head": tree.head, "clean": clean,
                            "dirty": [tree.ws(path) for path in dirty], "shallow": shallow})
            mods += _module_facts(tree, _source_modules(tree, ws.hub))
            entries += _entry_points(tree)
            commands += _commands(tree)
            ci_files += _ci(tree)
            configs |= _configs(tree)
            dirs, patterns = _tests(tree)
            test_dirs.update(dirs)
            test_patterns |= patterns
            docs += [tree.ws(path) for path in tree.files if _is_doc(path)]
            found_triggers += _source_triggers(tree)
            _register_packages(tree, imports)
            # The one pass that reads every hand-written code and doc blob.
            for path, text in tree.texts([p for p in tree.files if _term_file(p) or _mapper_candidate(p)]):
                if text is None or _is_generated(text):
                    continue
                if _term_file(path):
                    terms.add(tree, path, text)
                    entries += _main_entry(tree, path, text)
                    commands += _pep723_command(tree, path, text)
                if is_test_path(path):
                    continue
                if _language(path):
                    imports.add(tree.ws(path), text)
                named += [(kind, name, tree.ws(path), line) for kind, name, line in _code.resources_in(path, text)]
            co_change += _co_change(tree)

    module_paths = {m["path"] for m in mods}
    trigger_list = _trigger_facts(found_triggers, module_paths)
    per_module = Counter(t["module"] for t in trigger_list)
    for module in mods:
        module["triggers"] = per_module[module["path"]]
    deps, central = _dependency_facts(imports, module_paths)
    resources = _resource_facts(named, module_paths)
    best: dict[str, int] = {}
    for rank, path in entries:
        best[path] = min(rank, best.get(path, rank))
    entry_list = sorted(best, key=lambda p: (best[p], p.count("/"), p))
    commands.sort(key=lambda c: (c["locator"].count("/"), _loc_key(c["locator"])))
    docs = sorted(set(docs), key=lambda p: (p.count("/"), p))
    term_list, terms_truncated = terms.result(LIMITS["terms"])
    co_change.sort(key=lambda c: (-c["support"], -c["confidence"], c["a"], c["b"]))
    ranked_dirs = sorted(test_dirs, key=lambda d: (-test_dirs[d], d))[:MAX_TEST_DIRS]
    ci, ci_truncated = _bound_ci(ci_files)
    config_list, per_name = [], Counter()
    for kind, path in sorted(configs, key=lambda kp: (kp[1].count("/"), kp[1], kp[0])):
        # One file name repeated per module (tsconfig.json, spotbugs-exclude.xml)
        # says the same thing each time; keep the shallowest few.
        per_name[kind, _name(path)] += 1
        if per_name[kind, _name(path)] <= MAX_SAME_CONFIG:
            config_list.append((kind, path))

    def shown(key: str, items: list) -> list:
        return items[: LIMITS[key]]

    hints = {
        "triggers": (len(trigger_list) > LIMITS["triggers"],
                     (f"{LIMITS['triggers']} of {len(trigger_list)} trigger files shown; okf validate --json "
                     "lists every one no Workflow scope or Not covered row claims (trigger-coverage)")),
        "deps": (len(deps) > LIMITS["deps"],
                 (f"{LIMITS['deps']} of {len(deps)} module edges shown, most imports first; "
                 "read a module's imports with rg -n '^(import|from) ' <module>")),
        "central": (len(central) > LIMITS["central"],
                    f"{LIMITS['central']} of {len(central)} shared files shown, most importing modules first"),
        "resources": (len(resources) > LIMITS["resources"],
                      (f"{LIMITS['resources']} of {len(resources)} shared topics and tables shown; "
                      "rg -n '<name>' finds every use of one")),
        "entry_points": (len(entry_list) > LIMITS["entry_points"],
                         (f"{LIMITS['entry_points']} of {len(entry_list)} entry points shown, shallowest first; "
                         "triggers lists the framework entry points")),
        "terms": (terms_truncated, "more term candidates exist; read the glossary-like docs and enum types"),
        "commands": (len(commands) > LIMITS["commands"],
                     (f"{LIMITS['commands']} of {len(commands)} commands shown, shallowest first; "
                     "read the build files of the module you need")),
        "docs": (len(docs) > LIMITS["docs"],
                 f"{LIMITS['docs']} of {len(docs)} docs shown, shallowest first; git ls-files '*.md' lists all"),
        "ci": (ci_truncated, "more CI files or steps exist; read the CI directory"),
        "configs": (len(config_list) > LIMITS["configs"] or len(config_list) < len(configs),
                    "more lint, format and type configs exist (repeated per module); git ls-files lists them"),
        "co_change": (len(co_change) > MAX_CO_CHANGE,
                      f"{MAX_CO_CHANGE} of {len(co_change)} co-change pairs shown, strongest first"),
    }
    return {
        "sources": sources,
        "modules": sorted(mods, key=lambda m: m["path"]),
        "triggers": shown("triggers", trigger_list),
        "deps": shown("deps", deps),
        "central": shown("central", central),
        "resources": shown("resources", resources),
        "entry_points": shown("entry_points", entry_list),
        "commands": shown("commands", commands),
        "ci": ci,
        "configs": [
            {"kind": kind, "path": path}
            for kind, path in sorted(config_list[: LIMITS["configs"]])
        ],
        "tests": {"dirs": ranked_dirs, "patterns": sorted(test_patterns)},
        "docs": shown("docs", docs),
        "terms": term_list,
        "co_change": co_change[:MAX_CO_CHANGE],
        "truncated": {key: hint for key, (hit, hint) in hints.items() if hit},
    }


# --- triggers, dependencies and shared resources ----------------------------------------------


TRIGGER_KINDS = _code.TRIGGER_KINDS


@dataclass(frozen=True)
class Trigger:
    path: str  # workspace-relative file
    line: int
    kind: str  # one of _code.TRIGGER_KINDS


def triggers(
    ws: _config.Workspace,
    heads: dict[str, str] | None = None,
    listings: dict[str, list[str]] | None = None,
) -> list[Trigger]:
    """Every trigger at HEAD of every source: where requests, messages, schedules,
    events and commands enter production code (test and generated files excluded)."""
    found: list[Trigger] = []
    for source in ws.sources:
        with _git.BlobReader(source.path) as blobs:
            tree = _Tree(
                ws, source, blobs,
                (heads or {}).get(source.name), (listings or {}).get(source.name),
            )
            found += _source_triggers(tree)
    return sorted(found, key=lambda t: (t.path, t.line, t.kind))


def _source_triggers(tree: _Tree) -> list[Trigger]:
    hits = _git.grep_files(tree.source.path, tree.head, _code.TRIGGER_TOKENS)
    wanted = [
        path for path in tree.files
        if path in hits and _suffix(path) in _code.TRIGGER_SUFFIXES
        and not is_test_path(path) and not GENERATED_TOKEN.search(path)
    ]
    found = []
    for rel, text in tree.texts(wanted):
        if text is not None and not _is_generated(text):
            found += [Trigger(tree.ws(rel), line, kind) for line, kind in _code.triggers_in(rel, text)]
    return found


def _trigger_facts(found: list[Trigger], module_paths: set[str]) -> list[dict]:
    """One entry per trigger file: its module, kinds, trigger count and first line."""
    by_file: dict[str, list[Trigger]] = defaultdict(list)
    for trigger in found:
        by_file[trigger.path].append(trigger)
    facts = []
    for path, items in by_file.items():
        items.sort(key=lambda t: t.line)
        facts.append({
            "path": path,
            "module": owner(path, module_paths),
            "kinds": sorted({t.kind for t in items}, key=TRIGGER_KINDS.index),
            "count": len(items),
            "locator": _config.Locator(path, items[0].line, items[0].line).text(),
        })
    return sorted(facts, key=lambda f: (f["module"] or "", f["path"]))


def _register_packages(tree: _Tree, imports: _code.Imports) -> None:
    """Source root, workspace package names and Go module paths, for import resolution."""
    imports.root(tree.source.prefix)
    for rel in tree.files:
        name = _name(rel)
        if name == "package.json" and not is_test_path(rel) and not GENERATED_TOKEN.search(rel):
            package = _dict(_load("json", tree.text(rel))).get("name")
            if isinstance(package, str) and package:
                imports.package(package, tree.ws(rel))
        elif name == "go.mod" and not re.search(r"(^|/)(testdata|vendor|third_party)/", rel):
            found = re.search(r"^module\s+(\S+)", tree.text(rel) or "", re.MULTILINE)
            if found:
                imports.go_module(_unquote(found[1]), tree.ws(_parent(rel)))


def _mapper_candidate(rel: str) -> bool:
    """An XML file that may be a MyBatis mapper (its SQL names tables)."""
    return _suffix(rel) == ".xml" and not is_test_path(rel) and not GENERATED_TOKEN.search(rel)


def _dependency_facts(imports: _code.Imports, module_paths: set[str]) -> tuple[list[dict], list[dict]]:
    """Module edges (importing module -> imported module) and the files most modules import."""
    edges: dict[tuple[str, str], set[tuple[str, int]]] = defaultdict(set)
    importers: dict[str, set[str]] = defaultdict(set)
    statements: Counter = Counter()
    for path, line, target in imports.edges():
        source, dest = owner(path, module_paths), owner(target, module_paths)
        if source is None or dest is None or source == dest:
            continue
        edges[source, dest].add((path, line))
        importers[target].add(source)
        statements[target] += 1
    deps = []
    for (source, dest), sites in edges.items():
        path, line = min(sites)
        deps.append({
            "from": source, "to": dest, "count": len(sites),
            "locator": _config.Locator(path, line, line).text(),
            "mutual": (dest, source) in edges,
        })
    deps.sort(key=lambda d: (-d["count"], d["from"], d["to"]))
    central = [
        {"path": target, "module": owner(target, module_paths), "modules": len(users),
         "imports": statements[target]}
        for target, users in importers.items() if len(users) >= 2
    ]
    central.sort(key=lambda c: (-c["modules"], -c["imports"], c["path"]))
    return deps, central


def _resource_facts(named: list[tuple[str, str, str, int]], module_paths: set[str]) -> list[dict]:
    """Topics and tables named in two or more modules, with the first site per module."""
    sites: dict[tuple[str, str], dict[str, tuple[str, int]]] = defaultdict(dict)
    for kind, name, path, line in sorted(named, key=lambda n: (n[2], n[3])):
        module = owner(path, module_paths)
        if module is not None:
            sites[kind, name].setdefault(module, (path, line))
    out = []
    for (kind, name), by_module in sites.items():
        if len(by_module) < 2:
            continue
        out.append({
            "kind": kind, "name": name, "modules": sorted(by_module),
            "locators": [_config.Locator(p, n, n).text() for _, (p, n) in sorted(by_module.items())][:6],
        })
    return sorted(out, key=lambda r: (-len(r["modules"]), r["kind"], r["name"]))


def _bound_ci(files: list[dict]) -> tuple[list[dict], bool]:
    """At most ``ci_files`` files and ``ci_steps`` steps, shallowest files first."""
    files = sorted(files, key=lambda f: (f["file"].count("/"), f["file"]))
    out, budget, truncated = [], LIMITS["ci_steps"], False
    for item in files:
        if len(out) == LIMITS["ci_files"] or (budget == 0 and item["steps"]):
            truncated = True
            break
        steps = item["steps"][:budget]
        truncated |= len(steps) < len(item["steps"])
        budget -= len(steps)
        out.append({"file": item["file"], "steps": steps})
    return sorted(out, key=lambda f: f["file"]), truncated


def _loc_key(locator: str) -> tuple[str, int]:
    path, _, line = locator.partition("#L")
    return path.strip("<>"), int(line or 0)


def _module_facts(tree: _Tree, found: list[tuple[str, str | None]]) -> list[dict]:
    stats = {path: [0, Counter()] for path, _ in found}
    for rel in tree.files:
        home = owner(rel, stats)
        if home is None:
            continue
        stats[home][0] += 1
        language = _language(rel)
        if language:
            stats[home][1][language] += 1
    return [
        {
            "path": tree.ws(path),
            "source": tree.source.name,
            "manifest": tree.ws(manifest) if manifest else None,
            "files": stats[path][0],
            "languages": dict(sorted(stats[path][1].items(), key=lambda kv: (-kv[1], kv[0]))),
        }
        for path, manifest in found
    ]


# --- entry points ------------------------------------------------------------------


def _entry_points(tree: _Tree) -> list[tuple[int, str]]:
    """(rank, workspace path): 0 declared by a manifest, 1 conventional code, 2 specs."""
    out: list[tuple[int, str]] = []
    for rel in tree.files:
        name = _name(rel)
        low = name.lower()
        if name == "pyproject.toml":
            out += [(0, tree.ws(p)) for p in _pyproject_entries(tree, rel)]
        elif name == "package.json":
            out += [(0, tree.ws(p)) for p in _package_entries(tree, rel)]
        if is_test_path(rel) or GENERATED_TOKEN.search(rel):
            continue
        if low in ENTRY_BASENAMES or low.endswith(("application.java", "application.kt")):
            out.append((1, tree.ws(rel)))
        elif low in ENTRY_SPECS:
            out.append((2, tree.ws(rel)))
    return out


def _pyproject_entries(tree: _Tree, rel: str) -> list[str]:
    data = _dict(_load("toml", tree.text(rel)))
    project = _dict(data.get("project"))
    targets = list(_dict(project.get("scripts")).values())
    targets += list(_dict(project.get("gui-scripts")).values())
    targets += list(_dict(_dict(_dict(data.get("tool")).get("poetry")).get("scripts")).values())
    base = _parent(rel)
    out = []
    for target in targets:
        if not isinstance(target, str):
            continue
        module = target.split(":", 1)[0].strip().replace(".", "/")
        for candidate in (f"{module}.py", f"{module}/__main__.py", f"{module}/__init__.py",
                          f"src/{module}.py", f"src/{module}/__init__.py"):
            path = _join(base, candidate)
            if path in tree.fileset:
                out.append(path)
                break
    return out


def _package_entries(tree: _Tree, rel: str) -> list[str]:
    data = _dict(_load("json", tree.text(rel)))
    values = [data.get("main")]
    binary = data.get("bin")
    values += list(binary.values()) if isinstance(binary, dict) else [binary]
    base = _parent(rel)
    out = []
    for value in values:
        if isinstance(value, str) and (path := _norm(base, value)) in tree.fileset:
            out.append(path)
    return out


# --- commands -------------------------------------------------------------------------


def _commands(tree: _Tree) -> list[dict]:
    """Declared commands (scripts, targets, tasks) plus the conventional commands of
    each build tool. A command runs from its ``cwd`` (see command_cwd): the directory
    of the file its locator names.
    A conventional command already declared in that directory is left out."""
    out: list[dict] = []
    seen: set[tuple[str, str]] = set()
    for rel in sorted(tree.files, key=lambda p: (p.count("/"), p)):
        parser = COMMAND_FILES.get(_name(rel).lower())
        if parser is None:
            continue
        text = tree.text(rel)
        if text is None:
            continue
        try:
            found = parser(text)
        except (ValueError, yaml.YAMLError, AttributeError, TypeError):
            found = []
        runner = _js_runner(tree, rel, text) if _name(rel) == "package.json" else None
        for name, command, line in sorted(found, key=lambda item: (item[2], item[0])):
            kind = _kind(name, command)
            if runner:  # the script body is at the locator; the command is how to run it
                command = f"{runner} run {name}"
            seen.add((_parent(rel), command))
            out.append({"name": name, "command": command, "kind": kind, "locator": tree.loc(rel, line),
                        "cwd": command_cwd(rel, command)})
    for detect in BUILD_TOOLS:
        for rel, line, name, command, kind in detect(tree):
            if (_parent(rel), command) not in seen:
                seen.add((_parent(rel), command))
                out.append({"name": name, "command": command, "kind": kind,
                            "locator": tree.loc(rel, line), "cwd": command_cwd(rel, command)})
    return out


# Command kinds, checked in this order against the words of the name, then the command.
COMMAND_KINDS = (
    ("format", {"fmt", "format", "formatting", "prettier", "black", "isort", "spotless",
                "gofmt", "rustfmt", "scalafmt"}),
    ("typecheck", {"typecheck", "types", "typing", "mypy", "pyright", "tsc"}),
    ("lint", {"lint", "linter", "linting", "eslint", "ruff", "flake8", "pylint", "clippy",
              "vet", "checkstyle", "spotbugs", "pmd", "golangci", "rubocop", "stylelint",
              "biome", "detekt", "ktlint"}),
    ("test", {"test", "tests", "testing", "pytest", "jest", "vitest", "mocha", "karma",
              "ctest", "spec", "specs", "e2e", "integration", "coverage", "cov", "unittest",
              "playwright", "cypress"}),
    ("build", {"build", "compile", "package", "bundle", "dist", "assemble"}),
)
_NAME_ONLY_TEST = {"it", "its"}  # integration-test task names; too common as a word


def _kind(name: str, command: str) -> str:
    """build, test, lint, format, typecheck or other, from the name first."""
    for text, is_name in ((name, True), (command, False)):
        low = re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", text).lower()  # integrationTest
        words = set(re.findall(r"[a-z0-9]+", low))
        if "typecheck" in re.sub(r"[^a-z]", "", low):
            words.add("typecheck")
        if is_name:
            words |= {"test"} if words & _NAME_ONLY_TEST else set()
        words |= {"test" for word in words if word.startswith("test")}
        for kind, vocabulary in COMMAND_KINDS:
            if words & vocabulary:
                return kind
    return "other"


_JS_LOCKS = (
    ("pnpm-lock.yaml", "pnpm"), ("yarn.lock", "yarn"), ("bun.lockb", "bun"), ("bun.lock", "bun"),
    ("package-lock.json", "npm"), ("npm-shrinkwrap.json", "npm"),
)


def _js_runner(tree: _Tree, rel: str, text: str) -> str:
    """The package manager of a package.json: ``packageManager``, else the nearest lock."""
    declared = _dict(_load("json", text)).get("packageManager")
    if isinstance(declared, str) and declared.split("@", 1)[0] in ("npm", "pnpm", "yarn", "bun"):
        return declared.split("@", 1)[0]
    for directory in _ancestors(_parent(rel)):
        for lock, runner in _JS_LOCKS:
            if _join(directory, lock) in tree.fileset:
                return runner
    return "npm"


def _ancestors(directory: str):
    """``directory`` and each parent up to the source root "."."""
    while True:
        yield directory
        if directory == ".":
            return
        directory = _parent(directory)


# --- build-tool commands ----------------------------------------------------------------
#
# Each detector returns (source-relative file, line, name, command, kind). Build roots are
# the outermost build files: a Maven reactor child or a Cargo workspace member runs from
# its root. Fixture, example and generated build files are no build roots.

_FIXTURE = re.compile(r"(^|/)(src|examples?|samples?|node_modules|vendor|buildSrc)/")


def _fixture(rel: str) -> bool:
    return bool(_FIXTURE.search(rel) or is_test_path(rel) or GENERATED_TOKEN.search(rel))


def _build_roots(tree: _Tree, rank) -> list[tuple[str, str]]:
    """(directory, file) of the outermost build files, shallowest first.

    ``rank(name)`` orders the build file names of one directory (lower wins; None is
    not a build file); a directory below another build directory is left out.
    """
    best: dict[str, tuple[int, str]] = {}
    for rel in tree.files:
        order = rank(_name(rel))
        if order is None or _fixture(rel):
            continue
        directory = _parent(rel)
        if directory not in best or (order, rel) < best[directory]:
            best[directory] = (order, rel)
    out = []
    for directory in sorted(best, key=lambda d: (-1 if d == "." else d.count("/"), d)):
        if directory != "." and any(a in best for a in _ancestors(_parent(directory))):
            continue
        out.append((directory, best[directory][1]))
    return out


def _named(*names: str):
    return lambda name: names.index(name) if name in names else None


def _lines(tree: _Tree, rel: str) -> list[str]:
    return _files.text_lines(tree.text(rel) or "")


def _outer_tag_line(lines: list[str], tag: str) -> int | None:
    """The least indented ``<tag>`` line (a project's own, not a profile's)."""
    found = [(len(line) - len(line.lstrip()), index + 1)
             for index, line in enumerate(lines) if re.match(rf"^\s*<{tag}>", line)]
    return min(found)[1] if found else None


MAX_PROFILES = 3
MAVEN_PLUGINS = (  # (artifactId, goal, kind)
    ("spotless-maven-plugin", "spotless:check", "format"),
    ("maven-checkstyle-plugin", "checkstyle:check", "lint"),
    ("spotbugs-maven-plugin", "spotbugs:check", "lint"),
    ("maven-pmd-plugin", "pmd:check", "lint"),
)


def _maven_commands(tree: _Tree) -> list[tuple]:
    out = []
    for base, pom in _maven_roots(tree):
        text = tree.text(pom)
        if text is None:
            continue
        lines = _files.text_lines(text)
        mvn = "./mvnw" if _join(base, "mvnw") in tree.fileset else "mvn"
        line = _outer_tag_line(lines, "build") or _find(lines, r"<project\b") or 1
        out += [(pom, line, "test", f"{mvn} -q test", "test"),
                (pom, line, "verify", f"{mvn} -q verify", "build")]
        try:
            root = ElementTree.fromstring(text)
        except ElementTree.ParseError:
            root = None
        ids = [] if root is None else [
            (item.text or "").strip() for item in root.findall("./{*}profiles/{*}profile/{*}id")
        ]
        ids = [pid for pid in ids if re.fullmatch(r"[\w.-]+", pid)]
        if len(ids) <= MAX_PROFILES:
            start = (_find(lines, r"<profiles>") or 1) - 1
            for pid in ids:
                at = _find(lines, rf"<id>\s*{re.escape(pid)}\s*</id>", start) or line
                out.append((pom, at, f"verify -P{pid}", f"{mvn} -q verify -P{pid}", "build"))
        for artifact, goal, kind in MAVEN_PLUGINS:
            at = _find(lines, rf"<artifactId>\s*{re.escape(artifact)}\s*</artifactId>")
            if at:
                out.append((pom, at, goal, f"{mvn} -q {goal}", kind))
    return out


def _maven_roots(tree: _Tree) -> list[tuple[str, str]]:
    """(directory, pom) of every pom no other pom lists in its (or a profile's) modules."""
    poms = [rel for rel in tree.files if _name(rel) == "pom.xml" and not _fixture(rel)]
    children: set[str] = set()
    for pom in poms:
        try:
            root = ElementTree.fromstring(tree.text(pom) or "")
        except ElementTree.ParseError:
            continue
        items = root.findall("./{*}modules/{*}module") + root.findall(
            "./{*}profiles/{*}profile/{*}modules/{*}module")
        for item in items:
            path = _norm(_parent(pom), item.text or "")
            if path:
                children.add(_join(path, "pom.xml"))
    roots = [pom for pom in poms if pom not in children]
    return [(_parent(pom), pom) for pom in sorted(roots, key=lambda p: (p.count("/"), p))]


GRADLE_FILES = ("settings.gradle.kts", "settings.gradle", "build.gradle.kts", "build.gradle")
_GRADLE_TASK = re.compile(
    r"\btasks\s*\.\s*(?:register|create)\s*(?:<[^>\n]*>)?\s*\(\s*[\"']([\w.-]+)[\"']"
    r"|^\s*task\b\s*\(?\s*[\"']?([A-Za-z_][\w-]*)\b"
    r"|\bval\s+(\w+)\s+by\s+tasks\s*\.\s*(?:registering|creating)\b",
    re.MULTILINE,
)
_GRADLE_COMMENT = re.compile(r"(?<![:\"'])//[^\n]*|/\*.*?\*/", re.DOTALL)
GRADLE_PLUGINS = (  # (plugin pattern, task, kind)
    (r"com\.diffplug\.spotless|\bspotless\s*\{", "spotlessCheck", "format"),
    (r"[\"']checkstyle[\"']|\bcheckstyle\s*\{", "checkstyleMain", "lint"),
)


def _gradle_commands(tree: _Tree) -> list[tuple]:
    out = []
    roots = _build_roots(tree, _named(*GRADLE_FILES))
    for base, rel in roots:
        wrapper = "./gradlew" if _join(base, "gradlew") in tree.fileset else "gradle"
        lines = _lines(tree, rel)
        line = _find(lines, r"rootProject\.name|^\s*plugins\s*\{") or 1
        out += [(rel, line, "test", f"{wrapper} test", "test"),
                (rel, line, "build", f"{wrapper} build", "build")]
        for name in GRADLE_FILES[2:]:
            build = _join(base, name)
            text = tree.text(build) if build in tree.fileset else None
            for pattern, task, kind in GRADLE_PLUGINS if text else ():
                at = _find(_files.text_lines(text), pattern)
                if at:
                    out.append((build, at, task, f"{wrapper} {task}", kind))
    projects: dict[str, str] = {}  # project directory -> its build root
    for base, _ in roots:
        projects[base] = base
        for name in GRADLE_FILES[:2]:
            settings = _join(base, name)
            if settings in tree.fileset:
                for include in _gradle_includes(tree.text(settings) or ""):
                    if (path := _norm(base, include)):
                        projects.setdefault(path, base)
    for rel in tree.files:
        directory = _parent(rel)
        # build.gradle(.kts), or a script named after its project directory (a settings
        # file may set buildFileName, as Spring Framework's spring-core/spring-core.gradle)
        own = {f"{_name(directory)}.gradle", f"{_name(directory)}.gradle.kts"}
        if (_name(rel) not in GRADLE_FILES[2:] and _name(rel) not in own) or _fixture(rel):
            continue
        base = projects.get(directory)
        if base is None:
            continue  # not a project of any build
        depth = 0 if directory == base else directory.count("/") + 1 - (
            0 if base == "." else base.count("/") + 1)
        wrapper = ("./" if depth == 0 else "../" * depth) + "gradlew"
        if _join(base, "gradlew") not in tree.fileset:
            wrapper = "gradle"
        text = _GRADLE_COMMENT.sub(lambda m: re.sub(r"[^\n]", " ", m[0]), tree.text(rel) or "")
        for match in _GRADLE_TASK.finditer(text):
            name = match[1] or match[2] or match[3]
            out.append((rel, _line(text, match.start()), name, f"{wrapper} {name}",
                        _kind(name, "")))
    return out


def _cargo_commands(tree: _Tree) -> list[tuple]:
    out = []
    for base, rel in _build_roots(tree, _named("Cargo.toml")):
        lines = _lines(tree, rel)
        line = _find(lines, r"^\s*\[(workspace|package)\]") or 1
        out += [(rel, line, "build", "cargo build", "build"),
                (rel, line, "test", "cargo test", "test")]
        clippy = next((_join(base, n) for n in ("clippy.toml", ".clippy.toml")
                       if _join(base, n) in tree.fileset), None)
        lints = _find(lines, r"^\s*\[(workspace\.)?lints\.clippy\]|^\s*clippy\s*=|^\s*clippy\.")
        if clippy or lints:
            out.append((clippy or rel, 1 if clippy else lints, "clippy",
                        "cargo clippy --all-targets", "lint"))
        rustfmt = next((_join(base, n) for n in ("rustfmt.toml", ".rustfmt.toml")
                        if _join(base, n) in tree.fileset), None)
        if rustfmt:
            out.append((rustfmt, 1, "fmt", "cargo fmt --check", "format"))
    return out


_GOLANGCI = (".golangci.yml", ".golangci.yaml", ".golangci.toml", ".golangci.json")


def _go_commands(tree: _Tree) -> list[tuple]:
    """Every Go module runs its own ``./...``; nested modules are not covered by a parent."""
    out = []
    for rel in tree.files:
        if _name(rel) != "go.mod" or _fixture(rel):
            continue
        base = _parent(rel)
        line = _find(_lines(tree, rel), r"^\s*module\b") or 1
        out += [(rel, line, "test", "go test ./...", "test"),
                (rel, line, "vet", "go vet ./...", "lint")]
        config = next((_join(base, n) for n in _GOLANGCI if _join(base, n) in tree.fileset), None)
        if config:
            out.append((config, 1, "golangci-lint", "golangci-lint run", "lint"))
    return out


PY_TOOLS = {  # tool -> (command, kind)
    "pytest": ("pytest", "test"), "ruff": ("ruff check .", "lint"),
    "mypy": ("mypy .", "typecheck"), "pyright": ("pyright", "typecheck"),
    "black": ("black --check .", "format"), "isort": ("isort --check-only .", "format"),
    "flake8": ("flake8", "lint"),
}
_PY_LOCKS = (("uv.lock", "uv run "), ("poetry.lock", "poetry run "), ("pdm.lock", "pdm run "))
_INI_TOOLS = (  # (section regex, tool) in setup.cfg, tox.ini, pytest.ini, mypy.ini, .flake8
    (re.compile(r"^(tool:pytest|pytest)$"), "pytest"),
    (re.compile(r"^mypy$"), "mypy"),
    (re.compile(r"^flake8$"), "flake8"),
    (re.compile(r"^isort$|^tool:isort$"), "isort"),
)
_PY_CONFIG_FILES = {"pyproject.toml", "ruff.toml", ".ruff.toml", "pytest.ini", "mypy.ini",
                    ".mypy.ini", "pyrightconfig.json", ".flake8", "setup.cfg", "tox.ini"}


def _python_commands(tree: _Tree) -> list[tuple]:
    """Configured Python tools, run through uv, poetry or pdm when their lock is present."""
    out = []
    for rel in tree.files:
        name = _name(rel)
        if name not in _PY_CONFIG_FILES or _fixture(rel):
            continue
        text = tree.text(rel)
        if text is None:
            continue
        lines = _files.text_lines(text)
        found: dict[str, int] = {}  # tool -> line
        extra: list[tuple] = []
        if name == "pyproject.toml":
            found, extra = _pyproject_tools(rel, text, lines)
        elif name in ("ruff.toml", ".ruff.toml"):
            found["ruff"] = 1
            if (at := _find(lines, r"^\s*\[format\]")):
                extra.append((rel, at, "ruff format", "ruff format --check .", "format"))
        elif name == "pyrightconfig.json":
            found["pyright"] = 1
        else:
            for index, line in enumerate(lines):
                section = re.match(r"^\[([^\]]+)\]\s*$", line.strip())
                for regex, tool in _INI_TOOLS if section else ():
                    if regex.match(section[1].strip()) and tool not in found:
                        found[tool] = index + 1
            if name == ".flake8":
                found.setdefault("flake8", 1)
        if "mypy" in found and re.search(r"^\s*files\s*=", text, re.MULTILINE):
            mypy = "mypy"
        else:
            mypy = "mypy ."
        prefix = next((p for d in _ancestors(_parent(rel)) for lock, p in _PY_LOCKS
                       if _join(d, lock) in tree.fileset), "")
        for tool, line in sorted(found.items(), key=lambda kv: (kv[1], kv[0])):
            command, kind = PY_TOOLS[tool]
            command = mypy if tool == "mypy" else command
            out.append((rel, line, tool, prefix + command, kind))
        out += [(r, at, n, prefix + c if n == "ruff format" else c, k) for r, at, n, c, k in extra]
    return out


def _pyproject_tools(rel: str, text: str, lines: list[str]) -> tuple[dict[str, int], list[tuple]]:
    data = _dict(_load("toml", text))
    tool = _dict(data.get("tool"))
    found: dict[str, int] = {}
    for key in PY_TOOLS:
        if key in tool:
            found[key] = _find(lines, rf"^\s*\[tool\.{key}[.\]]") or 1
    for dep in _dev_dependencies(data):
        if dep in PY_TOOLS and dep not in found:
            found[dep] = _find(lines, rf"[\"']{re.escape(dep)}(?![\w-])|^\s*{re.escape(dep)}\s*=") or 1
    extra = []
    ruff = _dict(tool.get("ruff"))
    if "format" in ruff:
        at = _find(lines, r"^\s*\[tool\.ruff\.format\]") or found.get("ruff", 1)
        extra.append((rel, at, "ruff format", "ruff format --check .", "format"))
    for env in _dict(_dict(tool.get("tox")).get("env")):
        at = _find(lines, rf"^\s*\[tool\.tox\.env\.[\"']?{re.escape(env)}[\"']?\]") or 1
        extra.append((rel, at, env, f"tox -e {env}", _kind(env, "")))
    return found, extra


def _dev_dependencies(data: dict) -> set[str]:
    """Distribution names in dependency groups, extras and dev dependency tables."""
    specs: list = []
    for group in _dict(data.get("dependency-groups")).values():
        specs += _strings(group)
    for extra in _dict(_dict(data.get("project")).get("optional-dependencies")).values():
        specs += _strings(extra)
    tool = _dict(data.get("tool"))
    specs += _strings(_dict(tool.get("uv")).get("dev-dependencies"))
    poetry = _dict(tool.get("poetry"))
    specs += list(_dict(poetry.get("dev-dependencies")))
    for group in _dict(poetry.get("group")).values():
        specs += list(_dict(_dict(group).get("dependencies")))
    names = set()
    for spec in specs:
        match = re.match(r"\s*([A-Za-z0-9][A-Za-z0-9._-]*)", spec)
        if match:
            names.add(match[1].lower().replace("_", "-"))
    return names


def _dotnet_commands(tree: _Tree) -> list[tuple]:
    """Each solution builds and tests its projects; without one, each outermost project."""
    out = []
    solutions = [rel for rel in tree.files if _suffix(rel) in (".sln", ".slnx") and not _fixture(rel)]
    for rel in solutions:
        line = _find(_lines(tree, rel), r"^Project\(|<Project\b") or 1
        out += [(rel, line, "build", f"dotnet build {_name(rel)}", "build"),
                (rel, line, "test", f"dotnet test {_name(rel)}", "test")]
    if not solutions:
        for _, rel in _build_roots(tree, _dotnet_project):
            out += [(rel, 1, "build", "dotnet build", "build"), (rel, 1, "test", "dotnet test", "test")]
    return out


def _dotnet_project(name: str) -> int | None:
    return 0 if _suffix(name) in (".csproj", ".fsproj", ".vbproj") else None


def _cmake_commands(tree: _Tree) -> list[tuple]:
    out = []
    for _, rel in _build_roots(tree, _named("CMakeLists.txt")):
        lines = _lines(tree, rel)
        line = _find(lines, r"^\s*project\s*\(") or 1
        out += [(rel, line, "configure", "cmake -S . -B build", "build"),
                (rel, line, "build", "cmake --build build", "build")]
        testing = _find(lines, r"^\s*(enable_testing\s*\(|include\s*\(\s*CTest\b)")
        if testing:
            out.append((rel, testing, "ctest", "ctest --test-dir build", "test"))
    return out


BUILD_TOOLS = (
    _maven_commands, _gradle_commands, _cargo_commands, _go_commands, _python_commands,
    _dotnet_commands, _cmake_commands,
)


def _npm_scripts(text: str) -> list[tuple[str, str, int]]:
    scripts = _dict(_dict(json.loads(text)).get("scripts"))
    lines = _files.text_lines(text)
    start = _find(lines, r'^\s*"scripts"\s*:') or 1
    out = []
    for name, command in scripts.items():
        if isinstance(command, str):
            key = re.escape(json.dumps(name))
            out.append((name, command, _find(lines, rf"^\s*{key}\s*:", start - 1) or start))
    return out


_MAKE_TARGET = re.compile(r"^([A-Za-z0-9_][A-Za-z0-9_./-]*)\s*:(?!:?=)")


def _make(text: str) -> list[tuple[str, str, int]]:
    lines = _files.text_lines(text)
    out, seen = [], set()
    for index, line in enumerate(lines):
        match = _MAKE_TARGET.match(line)
        if not match or match[1] in seen:
            continue
        seen.add(match[1])
        command = None
        for following in lines[index + 1:]:
            if following.startswith("\t"):
                recipe = following.strip().lstrip("@-+").strip()
                if recipe and not recipe.startswith("#"):
                    command = recipe
                    break
            elif following.strip() and not following.lstrip().startswith("#"):
                break
        out.append((match[1], command or f"make {match[1]}", index + 1))
    return out


_JUST_RECIPE = re.compile(r"^@?([A-Za-z_][A-Za-z0-9_-]*)(?:\s+[^:]*)?:(?!=)")


def _just(text: str) -> list[tuple[str, str, int]]:
    lines = _files.text_lines(text)
    out = []
    for index, line in enumerate(lines):
        match = _JUST_RECIPE.match(line)
        if not match or match[1].startswith("_"):
            continue
        command = None
        for following in lines[index + 1:]:
            if following[:1] in (" ", "\t"):
                recipe = following.strip().lstrip("@-").strip()
                if recipe and not recipe.startswith("#"):
                    command = recipe
                    break
            elif following.strip():
                break
        out.append((match[1], command or f"just {match[1]}", index + 1))
    return out


def _taskfile(text: str) -> list[tuple[str, str, int]]:
    tasks = _dict(_dict(yaml.safe_load(text)).get("tasks"))
    lines = _files.text_lines(text)
    start = _find(lines, r"^tasks\s*:") or 1
    out = []
    for name, spec in tasks.items():
        name = str(name)
        line = _find(lines, rf"^\s+[\"']?{re.escape(name)}[\"']?\s*:", start) or start
        command = None
        if isinstance(spec, str):
            command = spec
        elif isinstance(spec, list) and spec and isinstance(spec[0], str):
            command = spec[0]
        elif isinstance(spec, dict):
            cmds = spec.get("cmds") or spec.get("cmd")
            first = cmds[0] if isinstance(cmds, list) and cmds else cmds
            if isinstance(first, dict):
                first = first.get("cmd") or (f"task {first['task']}" if first.get("task") else None)
            command = first if isinstance(first, str) else None
        out.append((name, (command or f"task {name}").strip().split("\n", 1)[0], line))
    return out


def _tox(text: str) -> list[tuple[str, str, int]]:
    lines = _files.text_lines(text)
    out = []
    for index, line in enumerate(lines):
        match = re.match(r"^\[testenv(?::([^\]]+))?\]\s*$", line.strip())
        if not match:
            continue
        name = match[1] or "testenv"
        command = None
        for offset, following in enumerate(lines[index + 1:], index + 1):
            if following.startswith("["):
                break
            cmd = re.match(r"^commands\s*=\s*(.*)$", following)
            if cmd:
                command = cmd[1].strip() or next(
                    (item.strip() for item in lines[offset + 1:] if item.strip()), None
                )
                break
        out.append((name, command or f"tox -e {name}", index + 1))
    return out


def _nox(text: str) -> list[tuple[str, str, int]]:
    lines = _files.text_lines(text)
    out = []
    for index, line in enumerate(lines):
        if not re.match(r"^\s*@nox\.session\b", line):
            continue
        override = re.search(r"name\s*=\s*['\"]([^'\"]+)['\"]", line)
        for position in range(index + 1, min(index + 10, len(lines))):
            match = re.match(r"^\s*(?:async\s+)?def\s+(\w+)", lines[position])
            if match:
                name = override[1] if override else match[1]
                out.append((name, f"nox -s {name}", position + 1))
                break
    return out


def _pyproject_tasks(text: str) -> list[tuple[str, str, int]]:
    data = tomllib.loads(text)
    tool = _dict(data.get("tool"))
    lines = _files.text_lines(text)
    out = []
    for section, table, runner in (
        ("tool.poe.tasks", _dict(_dict(tool.get("poe")).get("tasks")), "poe"),
        ("tool.pdm.scripts", _dict(_dict(tool.get("pdm")).get("scripts")), "pdm run"),
    ):
        for name, spec in table.items():
            if name.startswith("_"):
                continue
            command = _script_command(spec) or f"{runner} {name}"
            out.append((name, command, _toml_key_line(lines, section, name)))
    return out


def _script_command(spec) -> str | None:
    if isinstance(spec, dict):
        for key in ("cmd", "shell", "script", "call", "ref", "composite", "sequence"):
            if key in spec:
                spec = spec[key]
                break
    if isinstance(spec, list) and spec:
        spec = spec[0]
    if isinstance(spec, str) and spec.strip():
        return spec.strip().split("\n", 1)[0]
    return None


def _toml_key_line(lines: list[str], section: str, key: str) -> int:
    inside = False
    header = None
    for index, line in enumerate(lines):
        stripped = line.strip()
        if stripped in (f"[{section}.{key}]", f'[{section}."{key}"]'):
            return index + 1
        if stripped.startswith("["):
            inside = stripped == f"[{section}]"
            if inside:
                header = index + 1
            continue
        if inside and re.match(rf"^[\"']?{re.escape(key)}[\"']?\s*=", stripped):
            return index + 1
    return header or 1


COMMAND_FILES = {
    "package.json": _npm_scripts,
    "makefile": _make,
    "gnumakefile": _make,
    "justfile": _just,
    ".justfile": _just,
    "taskfile.yml": _taskfile,
    "taskfile.yaml": _taskfile,
    "tox.ini": _tox,
    "noxfile.py": _nox,
    "pyproject.toml": _pyproject_tasks,
}


# --- CI ---------------------------------------------------------------------------------


def _ci(tree: _Tree) -> list[dict]:
    out = []
    for rel in tree.files:
        name = _name(rel)
        if (rel.startswith(".github/workflows/") and rel.count("/") == 2
                and _suffix(rel) in (".yml", ".yaml")):
            parser = _github_steps
        elif rel == ".gitlab-ci.yml":
            parser = _gitlab_steps
        elif name == "Jenkinsfile":
            parser = _jenkins_steps
        else:
            continue
        text = tree.text(rel)
        if text is None:
            continue
        steps = [
            {"name": step_name, "run": run, "locator": tree.loc(rel, line)}
            for step_name, run, line in parser(text)
        ]
        out.append({"file": tree.ws(rel), "steps": steps})
    return out


_YAML_ONLY_BREAKS = re.compile(r"\r(?!\n)|[\x85\u2028\u2029]")


def _compose(text: str):
    # YAML also breaks lines at a lone CR, NEL, U+2028 and U+2029; git does not.
    # Blank them so node line numbers (locators) agree with git's line count.
    text = _YAML_ONLY_BREAKS.sub(" ", text)
    try:
        return yaml.compose(text, Loader=yaml.SafeLoader)
    except yaml.YAMLError:
        return None


def _pairs(node) -> list[tuple[str, int, object]]:
    """(key, 1-based key line, value node) of a YAML mapping node."""
    if not isinstance(node, yaml.MappingNode):
        return []
    return [
        (key.value, key.start_mark.line + 1, value)
        for key, value in node.value
        if isinstance(key, yaml.ScalarNode)
    ]


def _get(node, key: str):
    return next((value for name, _, value in _pairs(node) if name == key), None)


_SHELL_NOISE = re.compile(r"^(?:#|set\s+[-+]|shopt\s)")
MAX_RUN = 200


def _first_line(value: str) -> str:
    """The first command of a shell script: comments and ``set -e`` style lines
    skipped, backslash continuations joined, at most MAX_RUN characters."""
    lines = [line.strip() for line in value.splitlines()]
    for index, line in enumerate(lines):
        if not line or _SHELL_NOISE.match(line):
            continue
        parts = [line]
        while parts[-1].endswith("\\") and index + 1 < len(lines):
            parts[-1] = parts[-1][:-1].rstrip()
            index += 1
            parts.append(lines[index])
        command = " ".join(part for part in parts if part)
        return command if len(command) <= MAX_RUN else command[: MAX_RUN - 1] + "…"
    return ""


def _github_steps(text: str) -> list[tuple[str, str, int]]:
    out = []
    for job, _, spec in _pairs(_get(_compose(text), "jobs")):
        uses = next(((line, value) for key, line, value in _pairs(spec) if key == "uses"), None)
        if uses and isinstance(uses[1], yaml.ScalarNode):
            # A reusable workflow: the real steps live in another repository.
            out.append((job, f"uses {uses[1].value}", uses[0]))
            continue
        steps = _get(spec, "steps")
        for step in steps.value if isinstance(steps, yaml.SequenceNode) else []:
            fields = {key: (line, value) for key, line, value in _pairs(step)}
            run = fields.get("run")
            if run is None or not isinstance(run[1], yaml.ScalarNode):
                continue
            name = fields.get("name")
            label = name[1].value if name and isinstance(name[1], yaml.ScalarNode) else job
            out.append((label, _first_line(run[1].value), run[0]))
    return out


_GITLAB_RESERVED = {
    "stages", "variables", "default", "include", "workflow", "image", "services",
    "before_script", "after_script", "cache", "pages",
}


def _gitlab_steps(text: str) -> list[tuple[str, str, int]]:
    out = []
    for job, _, spec in _pairs(_compose(text)):
        if job.startswith(".") or job in _GITLAB_RESERVED:
            continue
        stack = [_get(spec, "script")]
        while stack:
            node = stack.pop(0)
            if isinstance(node, yaml.ScalarNode) and node.value.strip():
                out.append((job, _first_line(node.value), node.start_mark.line + 1))
            elif isinstance(node, yaml.SequenceNode) and node.tag != "!reference":
                stack = list(node.value) + stack
    return out


def _jenkins_steps(text: str) -> list[tuple[str, str, int]]:
    lines = _files.text_lines(text)
    steps = []
    stage = None
    for index, line in enumerate(lines):
        named = re.search(r"\bstage\s*\(\s*['\"]([^'\"]+)['\"]", line)
        if named:
            stage = named[1]
        match = re.search(r"\bsh\s*\(?\s*(?:script\s*:\s*)?('''|\"\"\"|'|\")(.*)$", line)
        if not match:
            continue
        quote, rest = match[1], match[2]
        if len(quote) == 3:
            run = rest.split(quote, 1)[0].strip() or next(
                (item.strip() for item in lines[index + 1:] if item.strip()), ""
            )
        else:
            run = rest.split(quote, 1)[0].strip()
        steps.append((stage or "sh", run, index + 1))
    return steps


# --- configs, tests, docs -----------------------------------------------------------------


def _configs(tree: _Tree) -> set[tuple[str, str]]:
    out: set[tuple[str, str]] = set()
    for rel in tree.files:
        name = _name(rel)
        low = name.lower()
        for kind, regex in _CONFIG_REGEX:
            if regex.match(low):
                out.add((kind, tree.ws(rel)))
        if rel.startswith(".husky/"):
            out.add(("precommit", tree.ws(rel)))
        if rel in (".vscode/settings.json", ".vscode/extensions.json"):
            out.add(("editor", tree.ws(rel)))
        kinds: set[str] = set()
        if name == "pyproject.toml":
            tool = _dict(_dict(_load("toml", tree.text(rel))).get("tool"))
            kinds = {PYPROJECT_TOOLS[key] for key in tool if key in PYPROJECT_TOOLS}
            if "format" in _dict(tool.get("ruff")):
                kinds.add("format")
        elif name in ("setup.cfg", "tox.ini"):
            for section in re.findall(r"^\[([^\]]+)\]", tree.text(rel) or "", re.MULTILINE):
                kinds |= {kind for regex, kind in INI_SECTIONS if regex.match(section.strip())}
        elif name == "package.json":
            data = _dict(_load("json", tree.text(rel)))
            kinds = {kind for key, kind in PACKAGE_JSON_KEYS.items() if key in data}
        elif name in ("pom.xml", "build.gradle", "build.gradle.kts"):
            text = tree.text(rel) or ""
            if "spotless" in text:
                kinds.add("format")
            if "checkstyle" in text:
                kinds.add("lint")
        out |= {(kind, tree.ws(rel)) for kind in kinds}
    return out


def _tests(tree: _Tree) -> tuple[Counter, set[str]]:
    dirs: Counter = Counter()
    patterns: set[str] = set()
    for rel in tree.files:
        if not _language(rel):
            continue  # docs, data and fixtures do not make a directory a test directory
        parts = _test_dirs(rel)  # src/main/... is production code even in a package named test
        in_root = False
        for index, part in enumerate(parts):
            if _test_root(part):
                dirs[tree.ws("/".join(parts[: index + 1]))] += 1
                in_root = True
                break
        pattern = _test_pattern(_name(rel), in_root)
        if pattern:
            patterns.add(pattern)
    return dirs, patterns


_NOT_TEST_CODE = {".sql", ".sh", ".bash", ".ps1"}  # fixtures and helper scripts


def _test_pattern(name: str, in_test_root: bool) -> str | None:
    """The test naming convention of a code file (``_test_name``), or ``Test*`` for a
    ``TestFoo`` file inside a test root; none for .sql and shell files."""
    suffix = PurePosixPath(name).suffix
    if suffix.lower() not in LANGUAGES or suffix.lower() in _NOT_TEST_CODE:
        return None
    if in_test_root and re.match(r"Test[A-Z][a-z]", name):
        return f"Test*{suffix}"
    return _test_name(name)


_DOC_STEMS = {"README", "CONTRIBUTING", "CHANGELOG", "ARCHITECTURE", "CONTEXT", "GLOSSARY",
              "TERMS", "DESIGN"}
_GLOSSARY_STEMS = {"GLOSSARY", "TERMS", "TERMINOLOGY", "CONTEXT"}


def _glossary_file(rel: str) -> bool:
    """A file whose name says it defines terms (GLOSSARY.md, docs/terms.md, CONTEXT.md)."""
    name = _name(rel)
    return name.split(".", 1)[0].upper() in _GLOSSARY_STEMS or "glossary" in name.lower()


_SKELETON_DIRS = {"templates", "assets"}


def _skeleton(rel: str) -> bool:
    """A file under a ``templates`` or ``assets`` directory (any depth, any case): page
    skeletons and bundled copies, not project documentation."""
    return any(part.lower() in _SKELETON_DIRS for part in rel.split("/")[:-1])


def _is_doc(rel: str) -> bool:
    if _skeleton(rel):
        return False
    name = _name(rel)
    suffix = _suffix(name)
    stem = name.split(".", 1)[0].upper()
    if stem in _DOC_STEMS and (suffix in DOC_SUFFIXES or "." not in name):
        return True
    if name.lower() in ("agents.md", "claude.md", "pull_request_template.md"):
        return True
    if suffix in (".md", ".mdx"):
        return rel.startswith("docs/") or _name(_parent(rel)) == "adr"
    return False


# --- terms -----------------------------------------------------------------------------------


_TERM_DOCS = {".md", ".mdx", ".markdown", ".rst"}
_JVM_MAIN = re.compile(
    r"\bstatic\s+(?:final\s+)?void\s+main\s*\(|^\s*fun\s+main\s*\(", re.MULTILINE
)


_COMMENT_LEAD = ("#", "//", "/*", "*", "<!--", "--", ";", "'''", '"""', "@")


def _is_generated(text: str) -> bool:
    """A generated-file header: a marker on a comment line near the top (prose such
    as "pages are generated by the extension" in a doc does not count)."""
    head = text[:2048].lower()
    if not any(marker in head for marker in GENERATED_MARKERS):
        return False
    return any(
        line.lstrip().startswith(_COMMENT_LEAD) and any(m in line for m in GENERATED_MARKERS)
        for line in head.split("\n")
    )


def _term_file(rel: str) -> bool:
    """Code and doc files outside generated or vendored directories."""
    suffix = _suffix(rel)
    return (suffix in LANGUAGES or suffix in _TERM_DOCS) and not GENERATED_TOKEN.search(rel)


_PY_MAIN = re.compile(r"""^if\s+__name__\s*==\s*["']__main__["']\s*:""", re.MULTILINE)
_PEP723 = re.compile(r"^# /// script\s*$", re.MULTILINE)
_EVAL_PATH = re.compile(r"(^|[/_.-])evals?([/_.-]|$)", re.IGNORECASE)


def _pep723_command(tree: _Tree, rel: str, text: str) -> list[dict]:
    """A PEP 723 script (inline ``# /// script`` metadata) runs with ``uv run <path>``
    from the source root; test and eval scripts are kind ``test``."""
    if _suffix(rel) != ".py" or "# /// script" not in text:
        return []
    found = _PEP723.search(text)
    if not found:
        return []
    name = PurePosixPath(rel).stem
    kind = _kind(name, "")
    if kind == "other" and (_EVAL_PATH.search(rel) or is_test_path(rel)):
        kind = "test"
    command = f"uv run {shlex.quote(rel)}"
    return [{"name": name, "command": command, "kind": kind,
             "locator": tree.loc(rel, _line(text, found.start())), "cwd": command_cwd(rel, command)}]


def _main_entry(tree: _Tree, rel: str, text: str) -> list[tuple[int, str]]:
    """Programs outside tests: a JVM ``main`` method, or a Python module guarded by
    ``if __name__ == "__main__":`` at top level."""
    if "__main__" in text and _suffix(rel) == ".py" and not is_test_path(rel):
        return [(1, tree.ws(rel))] if _PY_MAIN.search(text) else []
    if "main" not in text or _suffix(rel) not in (".java", ".kt", ".scala", ".groovy"):
        return []
    if is_test_path(rel) or not _JVM_MAIN.search(text):
        return []
    # Javadoc and string examples mention main(...) too; only real code counts.
    code = _C_NOISE.sub(lambda m: re.sub(r"[^\n]", " ", m[0]), text)
    return [(1, tree.ws(rel))] if _JVM_MAIN.search(code) else []


class _Terms:
    """Term candidates across all sources; files must be added in a fixed order.

    Kinds: ``defined`` (bold definitions in docs), ``state`` (enum-like types, with
    their first members) and ``camel`` (type names used across top-level
    directories). Each kind gets a fair share of the limit so one prolific kind
    cannot crowd out the others.
    """

    RANK: ClassVar[dict[str, int]] = {"defined": 0, "state": 1, "camel": 2}
    MAX_MEMBERS = 8

    def __init__(self):
        self.df: Counter = Counter()  # capitalized token -> number of files containing it
        self.tops: dict[str, set[str]] = defaultdict(set)  # camel token -> top-level dirs
        # lower term -> (rank, term, locator); rank = (not a glossary file, not a
        # definition-list entry), so the best definition site wins
        self.defined: dict[str, tuple[tuple[bool, bool], str, str]] = {}
        self.cjk_docs: list[str] = []  # docs with CJK text, for substring counts
        self.states: dict[str, tuple[str, list[str]]] = {}  # enum -> (locator, members)
        self.camels: dict[str, str] = {}
        self.doc_words: list[frozenset[str]] = []  # lowercased words of each doc

    def add(self, tree: _Tree, rel: str, text: str) -> None:
        suffix = _suffix(rel)
        if suffix in _TERM_DOCS and _skeleton(rel):
            return  # a page template (assets/templates/en/glossary.md) is not a term source
        if is_test_path(rel):
            # Test code and fixtures define no project terms and do not count toward
            # any kind's minimum (file counts, top-level spread).
            return
        tokens = set(_CAPITALIZED.findall(text))
        self.df.update(tokens)
        top = tree.ws(rel.split("/", 1)[0] if "/" in rel else ".")
        for token in tokens:
            if _CAMEL.fullmatch(token):
                self.tops[token].add(top)
        if suffix in _TERM_DOCS:
            self.doc_words.append(frozenset(_WORD.findall(text.lower())))
            if _CJK.search(text):
                self.cjk_docs.append(text.lower())
            self._bold(tree, rel, text)
        else:
            self._definitions(tree, rel, text, suffix)

    def _bold(self, tree: _Tree, rel: str, text: str) -> None:
        glossary = _glossary_file(rel)
        for match in _BOLD_DEF.finditer(text):
            term = (match[1] or match[2]).strip().rstrip(":：").strip()
            low = term.lower()
            if (
                not re.search(r"[A-Za-z\u3400-\u9fff]", term)
                or len(term.split()) > 5
                or low in DEFINED_STOP
                or term.endswith("?")
            ):
                continue
            start = text.rfind("\n", 0, match.start()) + 1
            before = text[start:match.start()]
            if _LIST_ITEM.match(before):
                continue  # "- **Performance:** ..." is a list item heading, not a term
            rank = (not glossary, not (before.strip() == "" and _defined_after(text, match.end())))
            best = self.defined.get(low)
            if best is None or rank < best[0]:
                self.defined[low] = (rank, term, tree.loc(rel, _line(text, match.start())))

    def _definitions(self, tree: _Tree, rel: str, text: str, suffix: str) -> None:
        for match in _TYPE_DEF.finditer(text):
            name = match[1]
            if _CAMEL.fullmatch(name) and name not in self.camels:
                self.camels[name] = tree.loc(rel, _line(text, match.start(1)))
        for name, pos, members in _enums(text, suffix):
            members = [m for m in dict.fromkeys(members) if len(m) >= 2 and not m.startswith("_")]
            if len(members) >= 2 and name not in self.states:
                self.states[name] = (tree.loc(rel, _line(text, pos)), members[: self.MAX_MEMBERS])

    def _doc_count(self, low: str) -> int:
        """Docs containing every word of the term (case-insensitive); a CJK term,
        which has no spaces between words, counts its occurrences in the docs."""
        if _CJK.search(low):
            return sum(doc.count(low) for doc in self.cjk_docs)
        words = _WORD.findall(low)
        if not words:
            return 0
        return sum(1 for doc in self.doc_words if all(word in doc for word in words))

    def result(self, limit: int) -> tuple[list[dict], bool]:
        """(at most ``limit`` candidates ordered by kind then count, truncated)."""
        by_kind: dict[str, list[dict]] = {kind: [] for kind in self.RANK}
        by_kind["defined"] = [
            {"term": term, "kind": "defined", "count": max(1, self._doc_count(low)), "locator": loc}
            for low, (_, term, loc) in self.defined.items()
        ]
        rank = {low: value[0] for low, value in self.defined.items()}
        by_kind["state"] = [
            {"term": name, "kind": "state", "count": self.df[name], "locator": loc, "members": members}
            for name, (loc, members) in self.states.items()
        ]
        by_kind["camel"] = [
            {"term": name, "kind": "camel", "count": self.df[name], "locator": loc}
            for name, loc in self.camels.items()
            if self.df[name] >= 3 and len(self.tops[name]) >= 2
        ]
        seen: set[str] = set()
        for kind in self.RANK:
            # Definitions in glossary files, then definition-list entries, come first.
            ranked = sorted(by_kind[kind], key=lambda c: (
                rank.get(c["term"].lower(), (False, False)) if kind == "defined" else (False, False),
                -c["count"], c["term"]))
            unique = []
            for candidate in ranked:
                key = candidate["term"].lower()
                if key not in seen:
                    seen.add(key)
                    unique.append(candidate)
            by_kind[kind] = unique
        total = sum(len(items) for items in by_kind.values())
        share = limit // len(self.RANK)
        chosen = {kind: items[:share] for kind, items in by_kind.items()}
        room = limit - sum(len(items) for items in chosen.values())
        for kind in self.RANK:  # hand unused shares to the higher-ranked kinds first
            extra = by_kind[kind][len(chosen[kind]): len(chosen[kind]) + room]
            chosen[kind] += extra
            room -= len(extra)
        out = [candidate for kind in self.RANK for candidate in chosen[kind]]
        return out, total > len(out)


def _defined_after(text: str, end: int) -> bool:
    """Definition text follows a bold term: on the same line, or on the next line."""
    line_end = text.find("\n", end)
    rest = text[end: len(text) if line_end < 0 else line_end].strip()
    if rest:
        return True
    if line_end < 0:
        return False
    following = text[line_end + 1:].split("\n", 1)[0].strip()
    return bool(following) and not following.startswith(("#", "**", "|", "```"))


def _enums(text: str, suffix: str) -> list[tuple[str, int, list[str]]]:
    """(type name, offset of the name, member names) of enum-like state types."""
    if suffix in (".py", ".pyi"):
        return _python_enums(text)
    if suffix == ".go":
        return _go_iota_enums(text)
    if suffix in _BRACE_ENUM_SUFFIXES and "enum" in text:
        return _brace_enums(text)
    return []


def _python_enums(text: str) -> list[tuple[str, int, list[str]]]:
    out = []
    for match in _PY_ENUM.finditer(text):
        if not _PY_ENUM_BASE.search(match[3]):
            continue
        class_indent = len(match[1].expandtabs())
        body_indent = None
        members = []
        for line in text[match.end():].split("\n")[1:]:
            if not line.strip() or line.lstrip().startswith("#"):
                continue
            indent = len(line) - len(line.lstrip())
            if indent <= class_indent:
                break
            body_indent = indent if body_indent is None else body_indent
            member = re.match(r"^\s*([A-Za-z_]\w*)\s*(?::[^=]*)?=(?!=)", line)
            if indent == body_indent and member:
                members.append(member[1])
        out.append((match[2], match.start(2), members))
    return out


def _go_iota_enums(text: str) -> list[tuple[str, int, list[str]]]:
    out = []
    for match in _GO_CONST.finditer(text):
        end = text.find("\n)", match.end())
        block = text[match.end(): end if end >= 0 else len(text)]
        typed = re.search(r"^\s*(\w+)\s+([\w.]+)\s*=\s*iota\b", block, re.MULTILINE)
        if not typed:
            continue
        members = re.findall(r"^[ \t]*([A-Za-z_]\w*)\b", block, re.MULTILINE)
        out.append((typed[2].rsplit(".", 1)[-1], match.end() + typed.start(1), members))
    return out


def _brace_enums(text: str) -> list[tuple[str, int, list[str]]]:
    clean = _C_NOISE.sub(lambda m: re.sub(r"[^\n]", " ", m[0]), text)
    out = []
    for match in _BRACE_ENUM.finditer(clean):
        depth = 0
        segment_start = match.end()
        members = []
        for pos in range(match.end(), len(clean)):
            char = clean[pos]
            if char in "([{":
                depth += 1
            elif char in ")]}" and depth:
                depth -= 1
            elif depth == 0 and char in ",;}":
                segment = clean[segment_start:pos]
                member = re.match(
                    r"\s*(?:@\w+(?:\([^)]*\))?\s*|#\[[^\]]*\]\s*)*(?:case\s+)?([A-Za-z_]\w*)",
                    segment,
                )
                if member:
                    members.append(member[1])
                segment_start = pos + 1
                if char != ",":
                    break
        out.append((match[1], match.start(1), members))
    return out


# --- co-change ---------------------------------------------------------------------------------


_BUILD_FILES = {name.lower() for name in MANIFESTS} | {
    "settings.gradle", "settings.gradle.kts", "gradle.properties", "go.work",
}


def _is_manifest(path: str) -> bool:
    return _name(path).lower() in _BUILD_FILES


def _is_lock(path: str) -> bool:
    name = _name(path).lower()
    return name in LOCK_NAMES or name.endswith(".lock")


def _co_change(tree: _Tree) -> list[dict]:
    single: Counter = Counter()
    pairs: Counter = Counter()
    for files in _git.log_name_only(tree.source.path, CO_CHANGE_COMMITS):
        if len(files) > CO_CHANGE_MAX_FILES:
            continue
        keep = sorted({f for f in files if f in tree.fileset and not _is_lock(f)})
        single.update(keep)
        pairs.update(combinations(keep, 2))
    out = []
    for (a, b), support in pairs.items():
        if support < CO_CHANGE_SUPPORT or (_is_manifest(a) and _is_manifest(b)):
            # Build manifests move together on every version bump; that is release
            # mechanics, not a coupling an agent needs to know about.
            continue
        confidence = max(support / single[a], support / single[b])
        if confidence >= CO_CHANGE_CONFIDENCE:
            out.append({"a": tree.ws(a), "b": tree.ws(b), "support": support,
                        "confidence": round(confidence, 2)})
    return out
