"""Stamp reviewed drafts, render the root index, record human verification and
render the AGENTS.md pointer block."""

import re
import shlex
from datetime import UTC, datetime
from pathlib import PurePosixPath

import _config
import _files
import _git
import _page
import _review
import _validate

INDEX = "index.md"
LOG = "log.md"
POINTER_BEGIN = "<!-- repo-wiki:begin -->"
POINTER_END = "<!-- repo-wiki:end -->"
POINTER_MAX_LINES = 15
INDEX_MAX_LINES = 150  # one index an agent reads whole; longer ones raise index-size
LOG_MAX_ENTRIES = 100
LOG_MAX_COMMITS = 400  # wiki commits read to derive the log
DERIVED_CODES = ("index", "log", "map")  # issues stamp itself resolves by rewriting the files

# (type, heading) groups of the root index of a single repository, and of a source index.
_SECTIONS = {
    "en": {
        "Architecture": "Architecture", "Overview": "Overview", "Glossary": "Glossary",
        "Conventions": "Conventions", "Map": "System map", "Flow": "Flows", "Workflow": "Workflows",
        "Module": "Modules", "Schema": "Database", "sources": "Sources",
    },
    "zh": {
        "Architecture": "架构", "Overview": "概览", "Glossary": "术语表", "Conventions": "开发规范",
        "Map": "系统契约图", "Flow": "跨仓流程", "Workflow": "流程", "Module": "模块",
        "Schema": "数据库", "sources": "源仓库",
    },
}
_ROOT_ORDER = ("Architecture", "Map", "Glossary", "Conventions", "Flow", "Workflow", "Module", "Schema")
_SOURCE_ORDER = ("Overview", "Conventions", "Workflow", "Module")
_TEXT = {
    "en": {
        "source_map": "Source map",
        "not_covered": "Not covered",
        "unmapped": "no page yet",
        "reviewed": "reviewed",
        "unreviewed": "unreviewed",
        "log_title": "Update log",
        "creation": "Creation",
        "update": "Update",
        "reviewed_by": "reviewed by",
        "log_older": "Older entries: `git log -- {wiki}`.",
        "map_title": "System map",
        "map_description": (
            "Generated from the code at HEAD: the contracts between the sources (routes, RPC services, "
            "topics, tables, libraries) with their providers, consumers and the pages that describe "
            "them. Read to see what depends on what; okf links --json queries it."
        ),
        "map_note": "Generated by okf stamp from the code at HEAD; do not edit. `okf links --json` queries it.",
        "map_contracts": "Contracts",
        "map_external": "External calls",
        "map_none": "No contracts between sources at HEAD.",
        "map_header": "| Contract | Provider | Consumers | Described in |",
        "map_external_header": "| Call | Consumers |",
        "pointer": [
            "## Repository knowledge layer",
            "Before changing code, open `{index}` and pick pages by description or by the",
            "Source map; check their claims in the cited source lines. Must read before",
            "naming or changing code: {must}.",
            "Before editing, run `okf impact --files <paths> --json` (okf: the repo-wiki",
            "skill's scripts/okf.py): pages to read and update, and change guide rows (where",
            "to start, what else to change, how to verify). After changing a page's `scope`",
            "files, update the page or mark it `status: draft` with a todo block. Invariant rows:",
            "`rg -nU '^\\|\\s*Invariant\\s*\\|.*\\n(\\|.*\\n)*' {wiki_arg}`",
        ],
        "and": " and ",
        "hub": ("In this hub, paste `okf pointer --source <name>` into each source's AGENTS.md "
                "(paths are relative to the hub root); okf never writes into sources."),
        "hub_source": ("Contracts with the other repositories: `{wiki}/system-map.md` and `okf links "
                       "--json`; follow their Change order. Paths are relative to the hub root."),
        "commands": "Verified commands:",
    },
    "zh": {
        "source_map": "源码映射",
        "not_covered": "未单独成页",
        "unmapped": "暂无页面",
        "reviewed": "已评审",
        "unreviewed": "未评审",
        "log_title": "更新日志",
        "creation": "新建",
        "update": "更新",
        "reviewed_by": "评审",
        "log_older": "更早的记录：`git log -- {wiki}`。",
        "map_title": "系统契约图",
        "map_description": (
            "由 HEAD 的代码生成：各源仓库之间的契约（路由、RPC 服务、主题、表、库），及其提供方、"
            "消费方和描述它们的页面。想知道谁依赖谁时阅读；用 okf links --json 查询。"
        ),
        "map_note": "由 okf stamp 根据 HEAD 的代码生成，请勿手改。用 `okf links --json` 查询。",
        "map_contracts": "契约",
        "map_external": "外部调用",
        "map_none": "HEAD 时各源仓库之间没有契约。",
        "map_header": "| 契约 | 提供方 | 消费方 | 描述页面 |",
        "map_external_header": "| 调用 | 消费方 |",
        "pointer": [
            "## 仓库知识层",
            "修改代码前先打开 `{index}`：按 description 或源码映射选页面，",
            "再到引用的源码行核实。命名或修改代码前必读：",
            "{must}。",
            "编辑前运行 `okf impact --files <paths> --json`（okf 即 repo-wiki skill 的",
            "scripts/okf.py）：列出要读的页面、要更新的页面和修改指南行",
            "（从哪里改、还要改什么、如何验证）。修改页面 `scope` 覆盖的文件后，",
            "同步更新页面，或将其标为 `status: draft` 并在 todo 块中写明变化。关键约束：",
            "`rg -nU '^\\|\\s*关键约束\\s*\\|.*\\n(\\|.*\\n)*' {wiki_arg}`",
        ],
        "and": " 和 ",
        "hub": "在 hub 中，把 `okf pointer --source <仓库>` 的输出粘贴到各源仓库的 AGENTS.md（路径相对 hub 根目录）；okf 从不写入源仓库。",
        "hub_source": "与其他仓库的契约见 `{wiki}/system-map.md` 和 `okf links --json`，改动按其中的变更顺序进行。路径相对 hub 根目录。",
        "commands": "已验证的命令：",
    },
}


class StampError(Exception):
    """User-facing; the message names the fix."""


def now() -> str:
    return datetime.now(UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z")


# --- derived files: indexes, log, System map ----------------------------------------


def render_derived(ws: _config.Workspace, pages: list[_page.Page], facts: _validate.Facts) -> dict[str, str]:
    """Wiki-relative path -> text of every file the kernel derives: the root index,
    one index per source directory in a hub, log.md and, in a hub, the System map."""
    out = render_indexes(ws, pages, facts)
    out[LOG] = render_log(ws, pages)
    if ws.hub:
        out[_page.MAP] = render_map(ws, pages, facts)
    return out


def derived_on_disk(ws: _config.Workspace) -> list[str]:
    """Derived files present in the wiki: every index.md and log.md, and the System map."""
    if not ws.wiki.is_dir():
        return []
    found = [
        file.relative_to(ws.wiki).as_posix()
        for file in ws.wiki.rglob("*.md")
        if file.is_file() and file.name in _page.RESERVED_NAMES
    ]
    if (ws.wiki / _page.MAP).is_file():
        found.append(_page.MAP)
    return sorted(found)


def write_derived(ws, pages, facts) -> list[str]:
    """Write the derived files that differ and remove stale ones; returns the changed paths."""
    expected = render_derived(ws, pages, facts)
    changed = []
    for path, text in expected.items():
        file = ws.wiki / path
        if file.is_file() and file.read_text(encoding="utf-8") == text:
            continue
        _files.atomic_text(file, text)
        changed.append(path)
    for path in derived_on_disk(ws):
        if path not in expected:
            (ws.wiki / path).unlink()
            changed.append(path)
    return sorted(changed)


def render_indexes(ws: _config.Workspace, pages: list[_page.Page], facts: _validate.Facts) -> dict[str, str]:
    """The root index.md and, in a hub, sources/<name>/index.md per source (OKF §8).
    Entries list stable pages only, with a trust marker; a hub's root index links each
    source directory instead of listing its pages."""
    text = _TEXT[ws.lang]
    heads = _SECTIONS[ws.lang]
    # The System map is listed from its rendering, not the file: stamp writes both at once.
    stable = [p for p in pages if p.status == "stable" and not p.error and p.type != "Map"]
    mapped = _validate.module_pages(facts, stable)
    excluded = _validate.module_exclusions(facts, pages)

    def entries(group, base: str) -> list[str]:
        group = sorted(group, key=lambda p: (str(p.meta.get("title")), p.path))
        return [
            f"* [{_one_line(p.meta.get('title'))}]({_rel(p.path, base)}) - "
            f"{_one_line(p.meta.get('description'))}{_trust(p, text)}"
            for p in group
        ]

    def sections(group_pages, order, base) -> list[str]:
        lines = []
        for type in order:
            found = entries([p for p in group_pages if p.type == type], base)
            if found:
                lines += [f"# {heads[type]}\n", *found, ""]
        return lines

    def source_map(modules, base) -> list[str]:
        if not modules:
            return []
        lines = [f"# {text['source_map']}\n"]
        for module in modules:
            label = "`./`" if module.path == "." else f"`{module.path}/`"
            covering = mapped.get(module.path) or []
            if covering:
                links = ", ".join(f"[{_one_line(p.meta.get('title'))}]({_rel(p.path, base)})" for p in covering)
                lines.append(f"* {label} - {links}")
            elif module.path in excluded:
                lines.append(f"* {label} - {text['not_covered']}: {_one_line(excluded[module.path])}")
            else:
                lines.append(f"* {label} - {text['unmapped']}")
        return lines + [""]

    out: dict[str, str] = {}
    if not ws.hub:
        body = sections(stable, _ROOT_ORDER, "") + source_map(facts.modules, "")
        out[INDEX] = _finish('---\nokf_version: "0.2"\n---\n', body)
        return out
    system = [p for p in stable if _page.path_source(ws, p.path) is None]
    body = sections(system, _ROOT_ORDER, "")
    map_entry = [f"# {heads['Map']}\n", f"* [{text['map_title']}]({_page.MAP}) - {text['map_description']}", ""]
    at = next((i for i, line in enumerate(body) if line.startswith(f"# {heads['Glossary']}")), len(body))
    body[at:at] = map_entry
    by_path = {p.path: p for p in stable}
    source_lines = []
    for source in ws.sources:
        overview = by_path.get(f"{_page.SOURCES_DIR}/{source.name}/overview.md")
        description = _one_line(overview.meta.get("description")) if overview else text["unmapped"]
        source_lines.append(f"* [{source.name}]({_page.SOURCES_DIR}/{source.name}/) - {description}")
        base = f"{_page.SOURCES_DIR}/{source.name}"
        own = [p for p in stable if _page.path_source(ws, p.path) == source.name]
        modules = [m for m in facts.modules if m.source == source.name]
        out[f"{base}/{INDEX}"] = _finish("", sections(own, _SOURCE_ORDER, base) + source_map(modules, base))
    body += [f"# {heads['sources']}\n", *source_lines, ""]
    out[INDEX] = _finish('---\nokf_version: "0.2"\n---\n', body)
    return dict(sorted(out.items()))


def _finish(head: str, lines: list[str]) -> str:
    return (head + "\n".join(lines)).rstrip("\n") + "\n"


def _rel(path: str, base: str) -> str:
    """A link from the index in ``base`` to ``path``: relative below it, bundle-absolute
    (``/flows/x.md``) to a page elsewhere, such as a Flow in a source's map."""
    if not base:
        return path
    return path[len(base) + 1:] if path.startswith(base + "/") else "/" + path


def _trust(page: _page.Page, text: dict) -> str:
    """`` (reviewed 2026-09-29)`` for a stamped page an approved review verified,
    `` (unreviewed ...)`` otherwise; nothing for generated pages."""
    if page.is_generated:
        return ""
    generated = page.meta.get("generated")
    at = generated.get("at") if isinstance(generated, dict) else None
    day = str(at)[:10] if at else ""
    reviewed = bool(page.meta.get("verified")) and _validate.stamped(page)
    word = text["reviewed"] if reviewed else text["unreviewed"]
    return f" ({word} {day})" if day else f" ({word})"


def _one_line(value) -> str:
    return " ".join(str(value or "").split())


def render_log(ws: _config.Workspace, pages: list[_page.Page]) -> str:
    """log.md (OKF §9): one entry per stamp that changed a page's stamped content, from
    the wiki's git history plus the stamps not yet committed; newest first, grouped by
    day. A projection of history, never a ledger: it is rebuilt the same way each time."""
    text = _TEXT[ws.lang]
    entries = _log_entries(ws, pages)
    lines = [f"# {text['log_title']}", ""]
    day = None
    for entry in entries[:LOG_MAX_ENTRIES]:
        if entry["at"][:10] != day:
            if day is not None:
                lines.append("")
            day = entry["at"][:10]
            lines += [f"## {day}", ""]
        kind = text["creation"] if entry["kind"] == "creation" else text["update"]
        revisions = ", ".join(entry["revisions"])
        reviewer = f"{text['reviewed_by']} {entry['reviewer']}" if entry["reviewer"] else text["unreviewed"]
        lines.append(
            f"* **{kind}**: [{_one_line(entry['title'])}](/{entry['path']}) - {revisions}; {reviewer}"
        )
    if len(entries) > LOG_MAX_ENTRIES:
        lines += ["", text["log_older"].replace("{wiki}", ws.wiki_rel)]
    return "\n".join(lines).rstrip("\n") + "\n"


def log_entries(ws: _config.Workspace, since: str | None = None, files: list[str] | None = None) -> dict:
    """The log as data (``okf log``): every stamp, newest first, optionally only those on or
    after ``since`` (YYYY-MM-DD) and only those of pages that cover or cite ``files``."""
    if since is not None and not re.fullmatch(r"\d{4}-\d{2}-\d{2}", since):
        raise StampError(f"--since {since!r} is not a date; use YYYY-MM-DD")
    entries = _log_entries(ws, _page.load_pages(ws))
    if since:
        entries = [e for e in entries if e["at"][:10] >= since]
    if files is not None:
        import _impact

        report = _impact.impact_files(ws, files)["files"]
        wanted = {page for item in report.values() for page in item["read"] + item["update"]}
        entries = [e for e in entries if e["path"] in wanted]
    return {"entries": entries}


def _stamp_of(meta: dict | None) -> tuple | None:
    """(content hash, generated.at, reviewer, revision, title) of a stamped page, else None."""
    if not isinstance(meta, dict) or meta.get("status") != "stable":
        return None
    stamp, generated = meta.get("stamp"), meta.get("generated")
    if not isinstance(stamp, dict) or not isinstance(generated, dict) or not stamp.get("content_sha256"):
        return None
    revision = meta.get("revision") if isinstance(meta.get("revision"), dict) else {}
    return (stamp["content_sha256"], str(generated.get("at") or ""), stamp.get("reviewed_by"),
            revision, meta.get("title") or "")


def _log_entries(ws, pages) -> list[dict]:
    import _frontmatter

    def meta_at(reader, rev: str, path: str) -> dict | None:
        data = reader.read(rev, f"{ws.wiki_rel}/{path}")
        if data is None:
            return None
        parsed = _frontmatter.parse_page(_files.normalize_newlines(data.decode("utf-8", errors="replace")))
        return None if parsed.errors else parsed.meta

    commits = _git.log_paths(ws.root, ws.wiki_rel, LOG_MAX_COMMITS)
    last: dict[str, tuple | None] = {}
    found: list[dict] = []

    def record(path: str, current: tuple | None) -> None:
        previous = last.get(path)
        if current is not None and (previous is None or previous[0] != current[0]):
            found.append({
                "path": path, "at": current[1], "reviewer": current[2], "title": current[4],
                "kind": "creation" if previous is None else "update",
                "revisions": _revision_range(previous[3] if previous else None, current[3]),
            })
        if current is not None:
            last[path] = current

    prefix = ws.wiki_rel + "/"
    with _git.BlobReader(ws.root) as reader:
        for sha, changed in reversed(commits):  # oldest first
            for full in changed:
                if not full.startswith(prefix):
                    continue
                path = full[len(prefix):]
                if not _page.is_page_path(path):
                    continue
                if path not in last:
                    last[path] = _stamp_of(meta_at(reader, f"{sha}^", path))  # None for a root commit
                record(path, _stamp_of(meta_at(reader, sha, path)))
    for page in pages:  # stamps not committed yet
        if page.error or page.is_generated:
            continue
        record(page.path, _stamp_of(page.meta))
    by_path = sorted(found, key=lambda e: e["path"])
    return sorted(by_path, key=lambda e: e["at"], reverse=True)  # newest first, then by path


def _revision_range(old: dict | None, new: dict) -> list[str]:
    out = []
    for name in sorted(new):
        rev = str(new[name])[:12]
        before = str((old or {}).get(name) or "")[:12]
        label = "" if name == "." else f"{name} "
        if old is None or not before:
            out.append(f"{label}{rev}")
        elif before != rev:
            out.append(f"{label}{before}..{rev}")
    return out or ["-"]


def render_map(ws: _config.Workspace, pages: list[_page.Page], facts: _validate.Facts) -> str:
    """system-map.md: the contracts between the sources at HEAD, rendered from scan,
    with the pages that claim each one. Kernel-owned like the database pages."""
    text = _TEXT[ws.lang]
    meta = {"type": "Map", "title": text["map_title"], "description": text["map_description"], "status": "stable"}
    claims: dict[str, list[_page.Page]] = {}
    for page in pages:
        if page.error or page.is_generated:
            continue
        for contract in _validate.claimed_contracts(ws, facts, page):
            claims.setdefault(contract.id, []).append(page)
    contracts = [c for c in facts.contracts if not c.external]
    external = [c for c in facts.contracts if c.external]
    names = {source.name: f"s{index}" for index, source in enumerate(ws.sources)}
    lines = [f"<!-- {text['map_note']} -->", ""]
    if not facts.contracts:
        lines.append(text["map_none"])
    if contracts:
        edges: dict[tuple[str, str], dict[str, int]] = {}
        for contract in contracts:
            for consumer in sorted({s.source for s in contract.consumers}):
                for provider in sorted({s.source for s in contract.providers}):
                    if consumer != provider:
                        kinds = edges.setdefault((consumer, provider), {})
                        kinds[contract.kind] = kinds.get(contract.kind, 0) + 1
        lines += ["```mermaid", "flowchart LR"]
        lines += [f'  {names[s.name]}["{s.name}"]' for s in ws.sources]
        for (consumer, provider), kinds in sorted(edges.items()):
            label = ", ".join(f"{kind} {count}" for kind, count in sorted(kinds.items()))
            lines.append(f"  {names[consumer]} -->|{label}| {names[provider]}")
        lines += ["```", "", f"## {text['map_contracts']}", "", text["map_header"], "|---|---|---|---|"]
        for contract in contracts:
            described = ", ".join(
                f"[{_one_line(p.meta.get('title'))}](/{p.path})" for p in sorted(claims.get(contract.id, []), key=lambda p: p.path)
            ) or "-"
            lines.append(
                f"| `{contract.id}` | {_sites(contract.providers)} | {_sites(contract.consumers)} | {described} |"
            )
    if external:
        lines += ["", f"## {text['map_external']}", "", text["map_external_header"], "|---|---|"]
        for contract in external:
            lines.append(f"| `{contract.id}` | {_sites(contract.consumers)} |")
    return _page.render_page(meta, "\n".join(lines).rstrip("\n") + "\n")


def _sites(sites) -> str:
    return "<br>".join(f"{site.source} `{site.locator}`" for site in sites) or "-"


# --- stamp ------------------------------------------------------------------------


def stamp(ws: _config.Workspace, by: str, unreviewed: bool = False) -> dict:
    if not _review.ACTOR.fullmatch(by or ""):
        raise StampError(f"--by {by!r} is not an actor; use repo-wiki/<model> or human:<id>")
    pages = _page.load_pages(ws)
    facts = _validate.Facts(ws)
    blocked: list[_validate.Issue] = []
    for source in ws.sources:
        clean, dirty = _git.is_clean(source.path, [] if ws.hub else [ws.wiki_rel])
        if not clean:
            blocked.append(
                _validate.Issue(
                    "dirty", "error", None, None,
                    f"source {source.name} has uncommitted changes: {', '.join(dirty[:10])}",
                    "Ask the user to commit or stash them; pages are stamped only against a commit.",
                )
            )
    issues = _validate.validate(ws, pages, facts=facts)
    blocked += [i for i in issues if i.severity in ("error", "pending") and i.code not in DERIVED_CODES]
    drafts = _review.drafts(pages)
    report = None
    requested = _review.open_changes(ws)
    if drafts and unreviewed and requested is not None:
        blocked.append(
            _validate.Issue(
                "review", "error", _review.REVIEW_FILE, None,
                f"{_review.REVIEW_FILE} requests changes ({requested} issues); --unreviewed "
                "cannot skip a review that found problems",
                "Repair the issues and run a fresh review round (okf review prepare --json), or "
                f"delete {_review.REVIEW_FILE} after resolving the issues with the user.",
            )
        )
    if drafts and not unreviewed:
        review_state, report = _review.state(ws, pages)
        if review_state != "approved":
            blocked.append(
                _validate.Issue(
                    "review", "error", _review.REVIEW_FILE, None,
                    f"review is {review_state}",
                    "Run okf review prepare --json and have a fresh reviewer write an approved report "
                    "for the current digest, or stamp with --unreviewed.",
                )
            )
    if blocked:
        return {"stamped": [], "blocked": [i.to_dict() for i in blocked]}

    at = now()
    stamped = []
    by_path = {p.path: p for p in pages}
    for page in drafts:
        meta = dict(page.meta)
        meta["status"] = "stable"
        meta["revision"] = dict(facts.head)  # equal source content, see Facts.current
        meta["sources"] = _page.sources_from_footnotes(page)
        meta["generated"] = {"by": by, "at": at}
        if report is not None:
            meta["verified"] = [{"by": report["reviewer"], "at": at}]
        else:
            meta.pop("verified", None)
        catalogs = _linked_catalogs(page, by_path)
        if catalogs:
            meta["catalogs"] = catalogs
        else:
            meta.pop("catalogs", None)
        meta.pop("stamp", None)
        page.meta = meta
        # The approving reviewer is part of the hash, so a reviewer entry added to
        # verified by hand (or an --unreviewed stamp dressed up as reviewed) fails
        # validation as an unreviewed edit.
        reviewer = report["reviewer"] if report is not None else None
        page.meta["stamp"] = {"content_sha256": page.content_sha256(reviewer), "reviewed_by": reviewer}
        _page.write_page(page)
        stamped.append(page.path)
    pages = _page.load_pages(ws)
    derived = write_derived(ws, pages, facts)
    pages = _page.load_pages(ws)
    review_file = ws.wiki / _review.REVIEW_FILE
    if review_file.exists():
        review_file.unlink()
    # Warnings never block a stamp; list them (with the stamped file lines) so they
    # stay visible after the pages turn stable.
    warnings = [i.to_dict() for i in _validate.validate(ws, pages, facts=facts) if i.severity == "warning"]
    return {
        "stamped": stamped,
        "verified_by": report["reviewer"] if report else None,
        "derived": [f"{ws.wiki_rel}/{path}" for path in derived],
        "warnings": warnings,
        "blocked": [],
    }


def linked_generated(page: _page.Page, by_path: dict[str, _page.Page]) -> list[_page.Page]:
    found = []
    base = PurePosixPath(page.path).parent
    for target, _ in page.structure.links:
        path = target.strip("<>").split("#", 1)[0]
        if not path or re.match(r"^[A-Za-z][A-Za-z0-9+.-]*:", path):
            continue
        rel = path.lstrip("/") if path.startswith("/") else (base / path).as_posix()
        other = by_path.get(PurePosixPath(rel).as_posix())
        if other is not None and other.is_generated and other not in found:
            found.append(other)
    return found


def _linked_catalogs(page, by_path) -> dict[str, str]:
    return {
        other.path: other.meta["catalog_sha256"]
        for other in linked_generated(page, by_path)
        if isinstance(other.meta.get("catalog_sha256"), str)
    }


# --- human verification ------------------------------------------------------------


def verify(ws: _config.Workspace, actor: str, paths: list[str]) -> dict:
    if not actor.startswith("human:") or not _review.ACTOR.fullmatch(actor):
        raise StampError(f"--actor {actor!r} must be human:<id>")
    at = now()
    done, already = [], []
    for path in paths:
        rel = path.removeprefix(ws.wiki_rel + "/")
        if not (ws.wiki / rel).is_file():
            raise StampError(f"{path} is not a wiki page")
        page = _page.load_page(ws, rel)
        if not _validate.stamped(page):
            raise StampError(
                f"{rel} is not a stable page matching its stamp (never stamped, or edited "
                "since); stamp it before recording a human review"
            )
        verified = page.meta.get("verified") or []
        if isinstance(verified, dict):
            verified = [verified]
        # A stamp resets verified, so an entry by this actor covers the current
        # stamped content: a second verify is a no-op; a verify after a re-stamp records.
        if any(isinstance(e, dict) and e.get("by") == actor for e in verified):
            already.append(rel)
            continue
        page.meta = dict(page.meta) | {"verified": [*verified, {"by": actor, "at": at}]}
        _page.write_page(page)
        done.append(rel)
    result = {"verified": done, "by": actor, "at": at}
    if already:
        result["already_verified"] = already
    return result


# --- AGENTS.md pointer ----------------------------------------------------------------


def pointer(ws: _config.Workspace, source: str | None = None) -> str:
    """The AGENTS.md block. In a hub, ``source`` makes the block for that source's
    AGENTS.md: its index and conventions, the system glossary and conventions, the
    System map; without it, the block for the hub's own AGENTS.md."""
    text = _TEXT[ws.lang]
    wiki = ws.wiki_rel
    names = [s.name for s in ws.sources]
    if source is not None and (not ws.hub or source not in names):
        raise StampError(
            f"--source {source!r} is not a source of this hub; use one of: {', '.join(names)}"
            if ws.hub else "--source is for a hub; a single repository has one pointer block"
        )
    index = f"{wiki}/{_page.SOURCES_DIR}/{source}/{INDEX}" if source else f"{wiki}/{INDEX}"
    must = [f"`{wiki}/glossary.md`", f"`{wiki}/conventions.md`"]
    if source:
        must.append(f"`{wiki}/{_page.SOURCES_DIR}/{source}/conventions.md`")
    must_text = (", " if ws.lang == "en" else "、").join(must[:-1]) + text["and"] + must[-1]
    lines = [POINTER_BEGIN]
    # The rg line is a shell command: a wiki path with spaces is quoted there.
    wiki_arg = shlex.quote(wiki)
    lines += [
        line.replace("{index}", index).replace("{must}", must_text)
        .replace("{wiki_arg}", wiki_arg).replace("{wiki}", wiki)
        for line in text["pointer"]
    ]
    if ws.hub:
        lines.append((text["hub_source"] if source else text["hub"]).replace("{wiki}", wiki))
    commands = _verified_commands(ws, source)
    room = POINTER_MAX_LINES - len(lines) - 1  # the end marker takes one line
    if commands and room >= 2:
        lines.append(text["commands"])
        lines += [f"- {purpose}: `{command}`" for purpose, command in commands[: room - 1]]
    lines.append(POINTER_END)
    return "\n".join(lines) + "\n"


def _verified_commands(ws, source: str | None = None) -> list[tuple[str, str]]:
    path = f"{_page.SOURCES_DIR}/{source}/conventions.md" if source else "conventions.md"
    if not (ws.wiki / path).is_file():
        return []
    page = _page.load_page(ws, path)
    if not _validate.stamped(page):  # a hand edit after stamp must not reach AGENTS.md
        return []
    found = []
    for table in _page.tables(page).get("commands", []):
        for row in table.rows:
            cells = [_validate._plain(c) for c in row.cells] + ["", "", ""]
            if cells[2] == "verified" and cells[1]:
                found.append((cells[0], cells[1]))
    return found


def write_pointer(ws: _config.Workspace, target, source: str | None = None) -> dict:
    file = ws.root / target
    # Symlinks are written through (CLAUDE.md -> AGENTS.md), but never out of the workspace.
    resolved = file.resolve()
    if not resolved.is_relative_to(ws.root.resolve()):
        raise StampError(
            f"{target} resolves to {resolved}, outside the workspace {ws.root}; pass a "
            "file inside the workspace, such as AGENTS.md"
        )
    block = pointer(ws, source)
    text = file.read_text(encoding="utf-8") if file.is_file() else ""
    start, end = text.find(POINTER_BEGIN), text.find(POINTER_END)
    if start >= 0 and end > start:
        new = text[:start] + block.rstrip("\n") + text[end + len(POINTER_END):]
        action = "replaced"
    else:
        new = (text.rstrip("\n") + "\n\n" if text.strip() else "") + block
        action = "appended"
    if new != text:
        _files.atomic_text(file, new)
    else:
        action = "unchanged"
    return {"file": str(target), "action": action}
